### ISSUE TITLE
Wrong spark-bigquery jar for v3.0.0-gcs-prometheus

### ISSUE THREAD

**Issue by armyhaylenko** [GoogleCloudPlatform/spark-on-k8s-operator#1016]
With spark 3.0.0 upgrade and consequent spark-operator upgrade, all of the processes that involved spark usage died with this error: 
```
java.util.ServiceConfigurationError: org.apache.spark.sql.sources.DataSourceRegister: Provider com.google.cloud.spark.bigquery.BigQueryRelationProvider could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:44)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike.filterImpl(TraversableLike.scala:255)
	at scala.collection.TraversableLike.filterImpl$(TraversableLike.scala:249)
	at scala.collection.AbstractTraversable.filterImpl(Traversable.scala:108)
	at scala.collection.TraversableLike.filter(TraversableLike.scala:347)
	at scala.collection.TraversableLike.filter$(TraversableLike.scala:347)
	at scala.collection.AbstractTraversable.filter(Traversable.scala:108)
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:644)
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSourceV2(DataSource.scala:728)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:230)
	at org.apache.spark.sql.DataFrameReader.json(DataFrameReader.scala:459)
	at org.apache.spark.sql.DataFrameReader.json(DataFrameReader.scala:382)
...
Caused by: java.lang.IllegalStateException:  This connector was made for Scala 2.11, it was not meant to run on Scala 2.12
	at com.google.cloud.spark.bigquery.BigQueryUtil$.validateScalaVersionCompatibility(BigQueryUtil.scala:118)
	at com.google.cloud.spark.bigquery.BigQueryRelationProvider.<init>(BigQueryRelationProvider.scala:36)
	at com.google.cloud.spark.bigquery.BigQueryRelationProvider.<init>(BigQueryRelationProvider.scala:43)
	at sun.reflect.GeneratedConstructorAccessor96.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	... 34 more
```
I took a look at Dockerfile for the image and there is one ADD [command](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/c19d2b8660d80ce561be28d76046ed60393a83d9/spark-docker/Dockerfile#L30) that I suspect breaks everything. If we refer to something that looks like [docs](https://github.com/googleclouddataproc/spark-bigquery-connector/#downloading-and-using-the-connector), it says that the jar name should be suffixed with _2.12 to refer to Scala 2.12 target jar. Is it meant to be that way in the dockerfile?
Thanks in advance.

**Comment by liyinan926** [comment]
Interesting, will look into this.

**Comment by armyhaylenko** [comment]
we rebuilt the image with 2.12 jar and it indeed worked, so for us the problem was definitely in the jar
