### ISSUE TITLE
Spark-pi Example fails - spec.containers[0].resources.requests: Invalid value: "1": must be less than or equal to cpu limit

### ISSUE THREAD

**Issue by ketanhdoshi** [GoogleCloudPlatform/spark-on-k8s-operator#1122]
The out-of-the-box Spark-pi example fails with the following exception:

```
Exception in thread "main" io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: 
https://10.96.0.1/api/v1/namespaces/spark-app/pods. Message: Pod "spark-pi-driver" is invalid: 
spec.containers[0].resources.requests: Invalid value: "1": must be less than or equal to cpu limit. Received status: 
Status(apiVersion=v1, code=422, details=StatusDetails(
causes=[StatusCause(field=spec.containers[0].resources.requests, message=Invalid value: "1": must be less than or equal to cpu limit, 
reason=FieldValueInvalid, additionalProperties={})], group=null, kind=Pod, name=spark-pi-driver, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, 
message=Pod "spark-pi-driver" is invalid: spec.containers[0].resources.requests: Invalid value: "1": must be less than or equal to cpu limit, 
metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), 
reason=Invalid, status=Failure, additionalProperties={}).
  at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:568)
  at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:507)
  at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:471)
  at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:430)
  at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:251)
  at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:815)
  at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:333)
  at org.apache.spark.deploy.k8s.submit.Client.$anonfun$run$2(KubernetesClientApplication.scala:130)
  at org.apache.spark.deploy.k8s.submit.Client.$anonfun$run$2$adapted(KubernetesClientApplication.scala:129)
  at org.apache.spark.util.Utils$.tryWithResource(Utils.scala:2539)
  at org.apache.spark.deploy.k8s.submit.Client.run(KubernetesClientApplication.scala:129)
  at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.$anonfun$run$4(KubernetesClientApplication.scala:221)
  at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.$anonfun$run$4$adapted(KubernetesClientApplication.scala:215)
  at org.apache.spark.util.Utils$.tryWithResource(Utils.scala:2539)
  at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.run(KubernetesClientApplication.scala:215)
  at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.start(KubernetesClientApplication.scala:188)
  at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:928)
  at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
  at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
  at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
  at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1007)
  at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1016)
  at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

I am following the [Quick Start](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/quick-start-guide.md) example with the latest version of Spark Operator.

I followed the Quick Start instructions to install the Operator as below. Even without setting sparkJobNamespace, the result is the same.

```
kubectl create namespace spark-app
helm repo add spark-operator https://googlecloudplatform.github.io/spark-on-k8s-operator
helm install sparkop spark-operator/spark-operator --namespace spark-operator --create-namespace --set sparkJobNamespace=spark-app
kubectl apply -f spark-pi.yaml
```

The spark-pi.yaml is as below. Only the volume hostpath, the service account, and the namespace have been modified.

```
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-pi
  namespace: spark-app
spec:
  type: Scala
  mode: cluster
  image: "gcr.io/spark-operator/spark:v3.0.0"
  imagePullPolicy: Always
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///opt/spark/examples/jars/spark-examples_2.12-3.0.0.jar"
  sparkVersion: "3.0.0"
  restartPolicy:
    type: Never
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/run/desktop/mnt/host/c/kd/dev/bd/volumes/spark"
        type: Directory
  driver:
    cores: 1
    coreLimit: "100m"
    memory: "512m"
    labels:
      version: 3.0.0
    serviceAccount: sparkop-spark
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
  executor:
    cores: 5
    instances: 1
    memory: "512m"
    labels:
      version: 3.0.0
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
```

This is with Kubernetes v 1.18.8 with Docker Desktop on Windows 10.

Thanks for any help you can provide!

**Comment by liyinan926** [comment]
The example you pasted above has a `coreLimit` that is well below the value of `cores`. You can try increasing `coreLimit` to `1200m`, which will make it valid.

**Comment by ketanhdoshi** [comment]
@liyinan926 , thanks very much for pointing out my mistake. I was able to reduce the CPU for the executor as below and get it to work. However, setting driver.cores to 0.1 or 100m doesn't work although [this issue](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/581) has a comment that suggests that it might. Is there a way to reduce the CPU for the driver? 

```
  driver:
    cores: 1
    coreLimit: "1200m"
    ...
  executor:
#    cores: 1
    coreRequest: 100m
    instances: 1
```

**Comment by liyinan926** [comment]
There's also a `coreRequest` under `driver` for setting the physical core request for the driver. You can set that to a value like `0.5` or `500m`.

**Comment by ketanhdoshi** [comment]
That was very helpful, I was able to use `driver.coreRequest`. I would suggest documenting this option for the driver and the executor. Thanks for your help!
