### ISSUE TITLE
IAM Role STS Assume Role Issue Service account

### ISSUE THREAD

**Issue by miloradtrninic** [GoogleCloudPlatform/spark-on-k8s-operator#1129]
Hello all, I am trying to run a Spark job in a AWS EKS cluster. I installed spark operator with helm and using webhook. I have a separate namespace for Spark jobs.
When I try to connect to S3 bucket using s3a interface I am getting an error saying Not authorized to perform sts:AssumeRoleWithWebIdentity 
I used settings provided in #1002 from @bbenzikry
Docker image: https://github.com/bbenzikry/spark-eks/blob/main/docker/spark3.Dockerfile
Role created using eksctl:`` eksctl create iamserviceaccount  --name eks-s3 --namespace spark-job  --cluster recommendation  --attach-policy-arn arn:aws:iam::aws:policy/AmazonS3FullAccess  --approve``
Job description:

```
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: data-prep
  namespace: spark-job
spec:
  type: Scala
  mode: cluster
  image: "spark:3.0.1"
  imagePullPolicy: Always
  mainClass: myMainClass
  mainApplicationFile: "local:///opt/spark/examples/jars/DataPrepare-assembly-0.1.jar"
  sparkVersion: "3.0.0"
  restartPolicy:
    type: Never
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
  hadoopConf:
    "fs.s3a.aws.credentials.provider": "com.amazonaws.auth.WebIdentityTokenCredentialsProvider"
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.0.0
    serviceAccount: my-release-spark
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
    securityContext:
      fsGroup: 65534
  executor:
    cores: 1
    instances: 4
    memory: "512m"
    labels:
      version: 3.0.0
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
    securityContext:
      fsGroup: 65534
```
Default SA in job namespace:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: MY_ARN
  creationTimestamp: "2021-01-13T12:16:19Z"
  name: default
  namespace: spark-job
  resourceVersion: "6616366"
  selfLink: /api/v1/namespaces/spark-job/serviceaccounts/default
secrets:
- name: default-token-v5v7c
```
Driver SA
```
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: MY_ROLE
    meta.helm.sh/release-name: my-release
    meta.helm.sh/release-namespace: spark-operator
  creationTimestamp: "2021-01-14T10:02:15Z"
  name: my-release-spark
  namespace: spark-job
  resourceVersion: "6616243"
  selfLink: /api/v1/namespaces/spark-job/serviceaccounts/my-release-spark
  uid: 02e37013-381c-4324-b216-5d28d36f729b
secrets:
- name: my-release-spark-token-zxpf7
```
Error log with jars used:
```
++ id -u
+ myuid=185
++ id -g
+ mygid=0
+ set +e
++ getent passwd 185
Jar folder: 
+ uidentry=
+ set -e
+ '[' -z '' ']'
+ '[' -w /etc/passwd ']'
+ echo '185:x:185:0:anonymous uid:/opt/spark:/bin/false'
+ SPARK_CLASSPATH=':/opt/spark/jars/*'
+ sed 's/[^=]*=\(.*\)/\1/g'
+ env
+ sort -t_ -k4 -n
+ grep SPARK_JAVA_OPT_
+ readarray -t SPARK_EXECUTOR_JAVA_OPTS
+ '[' -n '' ']'
+ '[' '' == 2 ']'
+ '[' '' == 3 ']'
+ '[' -n '' ']'
+ '[' -z ']'
+ case "$1" in
+ shift 1
+ CMD=("$SPARK_HOME/bin/spark-submit" --conf "spark.driver.bindAddress=$SPARK_DRIVER_BIND_ADDRESS" --deploy-mode client "$@")
+ exec /usr/bin/tini -s -- /opt/spark/bin/spark-submit --conf spark.driver.bindAddress=10.72.24.16 --deploy-mode client --properties-file /opt/spark/conf/spark.properties --class com.recommender.dataprepare.processing.Process spark-internal
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/opt/spark/jars/spark-unsafe_2.12-3.0.1.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
21/01/14 11:19:03 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Process started!
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
21/01/14 11:19:06 INFO SparkContext: Running Spark version 3.0.1
21/01/14 11:19:06 INFO ResourceUtils: ==============================================================
21/01/14 11:19:06 INFO ResourceUtils: Resources for spark.driver:

21/01/14 11:19:06 INFO ResourceUtils: ==============================================================
21/01/14 11:19:06 INFO SparkContext: Submitted application: DataPrepare
21/01/14 11:19:06 INFO SecurityManager: Changing view acls to: 185
21/01/14 11:19:06 INFO SecurityManager: Changing modify acls to: 185
21/01/14 11:19:06 INFO SecurityManager: Changing view acls groups to: 
21/01/14 11:19:06 INFO SecurityManager: Changing modify acls groups to: 
21/01/14 11:19:06 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(185); groups with view permissions: Set(); users  with modify permissions: Set(185); groups with modify permissions: Set()
21/01/14 11:19:07 INFO Utils: Successfully started service 'sparkDriver' on port 7078.
21/01/14 11:19:07 INFO SparkEnv: Registering MapOutputTracker
21/01/14 11:19:07 INFO SparkEnv: Registering BlockManagerMaster
21/01/14 11:19:07 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
21/01/14 11:19:07 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
21/01/14 11:19:07 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
21/01/14 11:19:07 INFO DiskBlockManager: Created local directory at /var/data/spark-488b3bc0-e05a-48bd-8cd1-444c20ce0630/blockmgr-16cea359-f918-49bb-ae79-6a8789759664
21/01/14 11:19:07 INFO MemoryStore: MemoryStore started with capacity 117.0 MiB
21/01/14 11:19:07 INFO SparkEnv: Registering OutputCommitCoordinator
21/01/14 11:19:07 INFO Utils: Successfully started service 'SparkUI' on port 4040.
21/01/14 11:19:07 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://data-prep-1610623136879-driver-svc.spark-job.svc:4040
21/01/14 11:19:08 INFO SparkContext: Added JAR file:///opt/spark/examples/jars/DataPrepare-assembly-0.1.jar at spark://data-prep-1610623136879-driver-svc.spark-job.svc:7078/jars/DataPrepare-assembly-0.1.jar with timestamp 1610623148028
21/01/14 11:19:08 INFO Executor: Starting executor ID driver on host data-prep-driver
21/01/14 11:19:08 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 7079.
21/01/14 11:19:08 INFO NettyBlockTransferService: Server created on data-prep-1610623136879-driver-svc.spark-job.svc:7079
21/01/14 11:19:08 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
21/01/14 11:19:08 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, data-prep-1610623136879-driver-svc.spark-job.svc, 7079, None)
21/01/14 11:19:08 INFO BlockManagerMasterEndpoint: Registering block manager data-prep-1610623136879-driver-svc.spark-job.svc:7079 with 117.0 MiB RAM, BlockManagerId(driver, data-prep-1610623136879-driver-svc.spark-job.svc, 7079, None)
21/01/14 11:19:08 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, data-prep-1610623136879-driver-svc.spark-job.svc, 7079, None)
21/01/14 11:19:08 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, data-prep-1610623136879-driver-svc.spark-job.svc, 7079, None)
21/01/14 11:19:09 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir ('file:/opt/spark/work-dir/spark-warehouse').
21/01/14 11:19:09 INFO SharedState: Warehouse path is 'file:/opt/spark/work-dir/spark-warehouse'.
21/01/14 11:19:11 WARN MetricsConfig: Cannot locate configuration: tried hadoop-metrics2-s3a-file-system.properties,hadoop-metrics2.properties
21/01/14 11:19:11 INFO MetricsSystemImpl: Scheduled Metric snapshot period at 10 second(s).
21/01/14 11:19:11 INFO MetricsSystemImpl: s3a-file-system metrics system started
Exception in thread "main" java.nio.file.AccessDeniedException: eu-central-1.com.recommendation: org.apache.hadoop.fs.s3a.auth.NoAuthWithAWSException: No AWS Credentials provided by WebIdentityTokenCredentialsProvider : com.amazonaws.services.securitytoken.model.AWSSecurityTokenServiceException: Not authorized to perform sts:AssumeRoleWithWebIdentity (Service: AWSSecurityTokenService; Status Code: 403; Error Code: AccessDenied; Request ID: ID; Proxy: null)
	at org.apache.hadoop.fs.s3a.S3AUtils.translateException(S3AUtils.java:187)
	at org.apache.hadoop.fs.s3a.Invoker.once(Invoker.java:111)
	at org.apache.hadoop.fs.s3a.Invoker.lambda$retry$3(Invoker.java:265)
	at org.apache.hadoop.fs.s3a.Invoker.retryUntranslated(Invoker.java:322)
	at org.apache.hadoop.fs.s3a.Invoker.retry(Invoker.java:261)
	at org.apache.hadoop.fs.s3a.Invoker.retry(Invoker.java:236)
	at org.apache.hadoop.fs.s3a.S3AFileSystem.verifyBucketExists(S3AFileSystem.java:375)
	at org.apache.hadoop.fs.s3a.S3AFileSystem.initialize(S3AFileSystem.java:311)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3303)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:124)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3352)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3320)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:479)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:361)
	at org.apache.spark.sql.execution.streaming.FileStreamSink$.hasMetadata(FileStreamSink.scala:46)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:366)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:297)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:286)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:286)
	at org.apache.spark.sql.DataFrameReader.csv(DataFrameReader.scala:723)
	at org.apache.spark.sql.DataFrameReader.csv(DataFrameReader.scala:553)
	at com.recommender.dataprepare.processing.LoadData$.csvLoad(LoadData.scala:20)
	at com.recommender.dataprepare.processing.Process$.main(Process.scala:14)
	at com.recommender.dataprepare.processing.Process.main(Process.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:928)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1007)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1016)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: org.apache.hadoop.fs.s3a.auth.NoAuthWithAWSException: No AWS Credentials provided by WebIdentityTokenCredentialsProvider : com.amazonaws.services.securitytoken.model.AWSSecurityTokenServiceException: Not authorized to perform sts:AssumeRoleWithWebIdentity (Service: AWSSecurityTokenService; Status Code: 403; Error Code: AccessDenied; Request ID: ID; Proxy: null)
	at org.apache.hadoop.fs.s3a.AWSCredentialProviderList.getCredentials(AWSCredentialProviderList.java:159)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.getCredentialsFromContext(AmazonHttpClient.java:1257)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.runBeforeRequestHandlers(AmazonHttpClient.java:833)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:783)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5062)
	at com.amazonaws.services.s3.AmazonS3Client.getBucketRegionViaHeadRequest(AmazonS3Client.java:5850)
	at com.amazonaws.services.s3.AmazonS3Client.fetchRegionFromCache(AmazonS3Client.java:5823)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5046)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5008)
	at com.amazonaws.services.s3.AmazonS3Client.headBucket(AmazonS3Client.java:1416)
	at com.amazonaws.services.s3.AmazonS3Client.doesBucketExist(AmazonS3Client.java:1352)
	at org.apache.hadoop.fs.s3a.S3AFileSystem.lambda$verifyBucketExists$1(S3AFileSystem.java:376)
	at org.apache.hadoop.fs.s3a.Invoker.once(Invoker.java:109)
	... 35 more
Caused by: com.amazonaws.services.securitytoken.model.AWSSecurityTokenServiceException: Not authorized to perform sts:AssumeRoleWithWebIdentity (Service: AWSSecurityTokenService; Status Code: 403; Error Code: AccessDenied; Request ID: ID; Proxy: null)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1811)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1395)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1371)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
	at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.doInvoke(AWSSecurityTokenServiceClient.java:1719)
	at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.invoke(AWSSecurityTokenServiceClient.java:1686)
	at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.invoke(AWSSecurityTokenServiceClient.java:1675)
	at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.executeAssumeRoleWithWebIdentity(AWSSecurityTokenServiceClient.java:1074)
	at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.assumeRoleWithWebIdentity(AWSSecurityTokenServiceClient.java:1045)
	at com.amazonaws.auth.STSAssumeRoleWithWebIdentitySessionCredentialsProvider.newSession(STSAssumeRoleWithWebIdentitySessionCredentialsProvider.java:149)
	at com.amazonaws.auth.STSAssumeRoleWithWebIdentitySessionCredentialsProvider.access$000(STSAssumeRoleWithWebIdentitySessionCredentialsProvider.java:40)
	at com.amazonaws.auth.STSAssumeRoleWithWebIdentitySessionCredentialsProvider$1.call(STSAssumeRoleWithWebIdentitySessionCredentialsProvider.java:65)
	at com.amazonaws.auth.STSAssumeRoleWithWebIdentitySessionCredentialsProvider$1.call(STSAssumeRoleWithWebIdentitySessionCredentialsProvider.java:62)
	at com.amazonaws.auth.RefreshableTask.refreshValue(RefreshableTask.java:257)
	at com.amazonaws.auth.RefreshableTask.blockingRefresh(RefreshableTask.java:213)
	at com.amazonaws.auth.RefreshableTask.getValue(RefreshableTask.java:154)
	at com.amazonaws.auth.STSAssumeRoleWithWebIdentitySessionCredentialsProvider.getCredentials(STSAssumeRoleWithWebIdentitySessionCredentialsProvider.java:130)
	at com.amazonaws.auth.STSAssumeRoleWithWebIdentitySessionCredentialsProvider.getCredentials(STSAssumeRoleWithWebIdentitySessionCredentialsProvider.java:40)
	at com.amazonaws.auth.profile.internal.securitytoken.STSProfileCredentialsServiceProvider.getCredentials(STSProfileCredentialsServiceProvider.java:71)
	at com.amazonaws.auth.WebIdentityTokenCredentialsProvider.getCredentials(WebIdentityTokenCredentialsProvider.java:76)
	at org.apache.hadoop.fs.s3a.AWSCredentialProviderList.getCredentials(AWSCredentialProviderList.java:137)
	... 53 more
21/01/14 11:19:14 INFO SparkContext: Invoking stop() from shutdown hook
21/01/14 11:19:14 INFO SparkUI: Stopped Spark web UI at http://data-prep-1610623136879-driver-svc.spark-job.svc:4040
21/01/14 11:19:14 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
21/01/14 11:19:14 INFO MemoryStore: MemoryStore cleared
21/01/14 11:19:14 INFO BlockManager: BlockManager stopped
21/01/14 11:19:14 INFO BlockManagerMaster: BlockManagerMaster stopped
21/01/14 11:19:14 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
21/01/14 11:19:14 INFO SparkContext: Successfully stopped SparkContext
21/01/14 11:19:14 INFO ShutdownHookManager: Shutdown hook called
21/01/14 11:19:14 INFO ShutdownHookManager: Deleting directory /tmp/spark-a56f5bed-3f34-4c81-9df9-906a3e67e084
21/01/14 11:19:14 INFO ShutdownHookManager: Deleting directory /var/data/spark-488b3bc0-e05a-48bd-8cd1-444c20ce0630/spark-a294d263-2d74-4446-b3ea-2ae160787fa3
```

**Comment by miloradtrninic** [comment]
Fixed: Remove conditions on Trust Policy on the Role or adjust to match service accounts.
