### ISSUE TITLE
Issues with hadoop-aws on upgrading to 3.0.0

### ISSUE THREAD

**Issue by kyprifog** [GoogleCloudPlatform/spark-on-k8s-operator#1213]
I upgraded spark to 3.0.0, but am having a persistent error that I cant seem to get rid of when trying to submit spark scala jobs which depend on S3 access to spark-operator:

``` 
2021-04-02 17:22:07,446 INFO  [main] handler.ContextHandler (ContextHandler.java:doStart(855)) - Started o.s.j.s.ServletContextHandler@7c891ba7{/static/sql,null,AVAILABLE,@Spark}
Exception in thread "main" java.lang.NoSuchMethodError: com.amazonaws.services.s3.transfer.TransferManager.<init>(Lcom/amazonaws/services/s3/AmazonS3;Ljava/util/concurrent/ThreadPoolExecutor;)V
	at org.apache.hadoop.fs.s3a.S3AFileSystem.initialize(S3AFileSystem.java:287)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2669)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2685)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
	at org.apache.spark.sql.execution.streaming.FileStreamSink$.hasMetadata(FileStreamSink.scala:46)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:361)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:279)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:268)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:268)
	at org.apache.spark.sql.DataFrameReader.csv(DataFrameReader.scala:705)
	at org.apache.spark.sql.DataFrameReader.csv(DataFrameReader.scala:535)
	at mason.spark.jobs.MergeJob$.run(MergeJob.scala:33)
	at mason.spark.configs.MergeConfig.run(MergeConfig.scala:54)
	at mason.spark.Main$.main(Main.scala:19)
	at mason.spark.Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:928)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1007)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1016)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

I've tried:
1.  Adding hadoop-aws (variety of versions but most recently 2.7.4) and aws-java-sdk (variety of versions but most recently 1.11.989) manually to the docker file in /opt/spark/jars/ and then adding the jars to the class path
2.  Creating a fat jar with these dependencies and submitting that to the spark-operator

I seem to get this error no matter what I try.  Any guidance?

**Comment by kyprifog** [comment]
Nevermind, I figured out that I needed to be using aws-java-sdk 1.7.4
