### ISSUE TITLE
Spark 3.1.1 Doesn't Update the driver spec

### ISSUE THREAD

**Issue by melvinRspectrumio** [GoogleCloudPlatform/spark-on-k8s-operator#1256]
Hello
I was confused why I am getting this

```
Caused by: com.amazonaws.SdkClientException: Unable to locate specified web identity token file: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
	at com.amazonaws.auth.STSAssumeRoleWithWebIdentitySessionCredentialsProvider.getWebIdentityToken(STSAssumeRoleWithWebIdentitySessionCredentialsProvider.java:159)
	at com.amazonaws.auth.STSAssumeRoleWithWebIdentitySessionCredentialsProvider.newSession(STSAssumeRoleWithWebIdentitySessionCredentialsProvider.java:146)
	
```

When I followed most of the instructions and validated 3 times its setup properly. 

Upon searching I saw that we need to add the `securityContext` to the driverspec

```
driver:
    serviceAccount: sap
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    hostNetwork: true
    labels:
      version: 3.1.1
    securityContext:
        fsGroup: 65534

```

upon submission, the sparkoperator creates the driver pod as expected but still getting the same issue as above and securityContext empty {}, why is it not applying the spec that was added on the driver?

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/psp: eks.privileged
  creationTimestamp: "2021-05-13T02:38:52Z"
  labels:
    spark-app-selector: spark-b63dd6bcf0c64c63b19bba7b4eb66b16
    spark-role: driver
    sparkoperator.k8s.io/app-name: sap-bone
    sparkoperator.k8s.io/launched-by-spark-operator: "true"
    sparkoperator.k8s.io/submission-id: 807e98dd-3509-4cc8-a63f-1889dd4418ed
  name: sap-bone
  namespace: default
  resourceVersion: "87748807"
  selfLink: /api/v1/namespaces/default/pods/sap-bone
  uid: 7b2d7048-f82c-4f29-8611-d898e99b1481
spec:
  containers:
  - args:
    - driver
    - --properties-file
    - /opt/spark/conf/spark.properties

.......

    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/data/spark-85313090-13c8-4c1a-9eac-cb8d07e9ab1a
      name: spark-local-dir-1
    - mountPath: /opt/spark/conf
      name: spark-conf-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: app-token-8pfhd
      readOnly: true
    - mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
      name: aws-iam-token
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: regcred
  nodeName: ip-xx-xxx-xx-xxx.us-west-2.compute.internal
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: sap
  serviceAccountName: sap
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: aws-iam-token
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          audience: sts.amazonaws.com
          expirationSeconds: 86400
          path: token


```

Is this a regression?

**Comment by melvinRspectrumio** [comment]
I think this is related to https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/1235

**Comment by melvinRspectrumio** [comment]
reading the code and some docs, it looks like for this to work we need to add the webhook 

```
helm --install spark-k8s-operator spark-operator/spark-operator --set image.tag=v1beta2-1.2.3-3.1.1 --set webhook.enable=true 
```

good to close for now. 

Thanks
