### ISSUE TITLE
gcr.io/spark-operator/spark:v3.1.1 dependency hell

### ISSUE THREAD

**Issue by woj-i** [GoogleCloudPlatform/spark-on-k8s-operator#1334]
Hi!
I try to run an app using following (maven) dependencies:
```
...
    <properties>
        <scala.binary.version>2.12</scala.binary.version>
        <spark.version>3.1.1</spark.version>
        <hadoop.version>3.2.0</hadoop.version>
        <aws-sdk.version>2.17.24</aws-sdk.version>
    </properties>
...
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-sql_${scala.binary.version}</artifactId>
            <version>${spark.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.hadoop</groupId>
            <artifactId>hadoop-aws</artifactId>
            <version>${hadoop.version}</version>
        </dependency>
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>bom</artifactId>
            <version>${aws-sdk.version}</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>s3</artifactId>
            <version>${aws-sdk.version}</version>
        </dependency>
...
```
I dockerized it with the base image `gcr.io/spark-operator/spark:v3.1.1` as I haven't found the `v3.1.1-gcs-prometheus` mentioned in examples (someone already raised it here https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/1266).

When the app is submitted I get:
```
Exception in thread "main" java.lang.NoSuchMethodError: 'long org.apache.hadoop.conf.Configuration.getTimeDuration(java.lang.String, java.lang.String, java.util.concurrent.TimeUnit)'
	at org.apache.hadoop.fs.s3a.S3ARetryPolicy.<init>(S3ARetryPolicy.java:114)
	at org.apache.hadoop.fs.s3a.S3AFileSystem.initialize(S3AFileSystem.java:260)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2669)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2685)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
	at org.apache.spark.sql.execution.streaming.FileStreamSink$.hasMetadata(FileStreamSink.scala:46)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:376)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:326)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$3(DataFrameReader.scala:308)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:308)
	at org.apache.spark.sql.DataFrameReader.parquet(DataFrameReader.scala:834)
	at org.apache.spark.sql.DataFrameReader.parquet(DataFrameReader.scala:806)
	at ai.humn.eod.extractor.GenericExtractor$.getRawData(GenericExtractor.scala:64)
	at ai.humn.eod.extractor.GenericExtractor$.main(GenericExtractor.scala:30)
	at ai.humn.eod.extractor.GenericExtractor.main(GenericExtractor.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:951)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1030)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1039)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

The above looks like mismatch of versions of dependencies in `hadoop-common` package. I use `<hadoop.version>3.2.0</hadoop.version>` as you can see in `properties` section. I can see Hadoop 3.2.0 in dependencies of spark-sql 3.1.1.

I am confused, because it looks like versions of spark and hadoop should match between the docker image (I use `gcr.io/spark-operator/spark:v3.1.1` as my base image) and the app jar, but they don't. 

My plan is to find dockerfile of `gcr.io/spark-operator/spark:v3.1.1` and find the difference, then create my dockerfile modified with matched versions of `hadoop-common`. However, I can't find the dockerimage of `gcr.io/spark-operator/spark:v3.1.1`. Is it available somewhere? If not would you recommend any other image to use as a base image for spark 3.1.1 applications run on spark-operator?

**Comment by woj-i** [comment]
Thank you @gauravbh1, it helped me.
