### ISSUE TITLE
Random KubernetesClientException: Operation: [create]  for kind: [Pod]  with name: [null]  in namespace: [XXX]  failed.

### ISSUE THREAD

**Issue by sk-ilya** [GoogleCloudPlatform/spark-on-k8s-operator#1357]
Hello, sometimes my jobs are failing to deploy with 
`io.fabric8.kubernetes.client.KubernetesClientException: Operation: [create]  for kind: [Pod]  with name: [null]  in namespace: [spark-operator]  failed.`

Sometimes I need to delete a spark app with kubectl delete sparkapplications.sparkoperator.k8s.io and deploy it again several times.
Also, drivers can throw this error randomly while creating executors.

Full stack trace:

```
I0922 16:38:55.528978       9 event.go:282] Event(v1.ObjectReference{Kind:"SparkApplication", Namespace:"spark-operator", Name:"JOB_NAME", UID:"da0b2d7e-16ee-45aa-b275-91b245c696ec", APIVersion:"sparkoperator.k8s.io/v1beta2", ResourceVersion:"62187048", FieldPath:""}): type: 'Warning' reason: 'SparkApplicationSubmissionFailed' failed to submit SparkApplication JOB_NAME: failed to run spark-submit for SparkApplication spark-operator/JOB_NAME: WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/opt/spark/jars/spark-unsafe_2.12-3.1.1.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
21/09/22 16:38:40 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
21/09/22 16:38:41 INFO SparkKubernetesClientFactory: Auto-configuring K8S client using current context from users K8S config file
21/09/22 16:38:43 INFO KerberosConfDriverFeatureStep: You have not specified a krb5.conf file locally or via a ConfigMap. Make sure that you have the krb5.conf locally on the driver image.
Exception in thread "main" io.fabric8.kubernetes.client.KubernetesClientException: Operation: [create]  for kind: [Pod]  with name: [null]  in namespace: [spark-operator]  failed.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:72)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:349)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:84)
	at org.apache.spark.deploy.k8s.submit.Client.run(KubernetesClientApplication.scala:139)
	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.$anonfun$run$3(KubernetesClientApplication.scala:213)
	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.$anonfun$run$3$adapted(KubernetesClientApplication.scala:207)
	at org.apache.spark.util.Utils$.tryWithResource(Utils.scala:2611)
	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.run(KubernetesClientApplication.scala:207)
	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.start(KubernetesClientApplication.scala:179)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:951)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1030)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1039)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.net.SocketTimeoutException: timeout
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:672)
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:680)
	at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.java:153)
	at okhttp3.internal.http2.Http2Codec.readResponseHeaders(Http2Codec.java:131)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at io.fabric8.kubernetes.client.utils.BackwardsCompatibilityInterceptor.intercept(BackwardsCompatibilityInterceptor.java:135)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at io.fabric8.kubernetes.client.utils.OIDCTokenRefreshInterceptor.intercept(OIDCTokenRefreshInterceptor.java:41)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:68)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at io.fabric8.kubernetes.client.utils.HttpClientUtils.lambda$createHttpClient$3(HttpClientUtils.java:151)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
	at okhttp3.RealCall.execute(RealCall.java:93)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:490)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:451)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:252)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:879)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:341)
	... 14 more
21/09/22 16:38:55 INFO ShutdownHookManager: Shutdown hook called
21/09/22 16:38:55 INFO ShutdownHookManager: Deleting directory /tmp/spark-b159fbac-a6b7-469c-a311-0ecbec42c790
I0922 16:38:55.550128       9 controller.go:223] SparkApplication spark-operator/JOB_NAME was updated, enqueuing it
I0922 16:38:55.550573       9 controller.go:270] Ending processing key: "spark-operator/JOB_NAME"
I0922 16:38:55.550593       9 controller.go:263] Starting processing key: "spark-operator/JOB_NAME"
I0922 16:38:55.550631       9 controller.go:270] Ending processing key: "spark-operator/JOB_NAME"
I0922 16:38:59.087007       9 controller.go:165] Syncing ScheduledSparkApplication spark-operator/OTHER_JOB_NAME
I0922 16:39:04.959225       9 controller.go:223] SparkApplication spark-operator/JOB_NAME was updated, enqueuing it
I0922 16:39:04.959285       9 controller.go:263] Starting processing key: "spark-operator/JOB_NAME"
I0922 16:39:04.959366       9 controller.go:270] Ending processing key: "spark-operator/JOB_NAME"
```

Spark job spec:
```
apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: JOB_NAME
  namespace: spark-operator
spec:
  type: Scala
  mode: cluster
  image: XXXXXXXX
  imagePullPolicy: Always
  mainClass: example.JobClassName
  mainApplicationFile: local:///opt/spark/job/spark_job.jar
  sparkVersion: 3.0.1
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  driver:
    cores: 1
    memory: 512m
    labels:
      version: 3.0.1
    serviceAccount: sa-spark
  executor:
    cores: 1
    instances: 1
    memory: 512m
    labels:
      version: 3.0.1
  dynamicAllocation:
    enabled: true
    initialExecutors: 1
    minExecutors: 1
    maxExecutors: 3
    cachedExecutorIdleTimeout: "60s"
  sparkConfigMap: "spark-defaults"
  sparkConf:
    "spark.app.name" : "JOB_NAME"
    "spark.sql.streaming.query.checkpointLocation": "XXXXXXXX"
```

DOCKERFILE:

```
FROM gcr.io/spark-operator/spark:v3.0.0-hadoop3

ADD target/scala-2.12/"spark_job.jar" /opt/spark/job/
```

Jobs are written in scala 2.12.11, sbt 1.5.0. Spark operator v1beta2-1.2.3-3.1.1 (helm.sh/chart: spark-operator-1.1.6)

**Comment by FloraZhang** [comment]
I'm having same issue. It happened randomly.

**Comment by zeotap-nipunj** [comment]
Facing this same issue while running on GKE with mutating admission webhook enabled. The issue disappear when operator is installed with webhook disabled

**Comment by zeotap-nipunj** [comment]
@liyinan926 Could you help with this or tag someone who can help with this issue?

**Comment by zeotap-nipunj** [comment]
Issue resolved after setting up Mutating webhook correctly for a private GKE cluster as mentioned here: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/quick-start-guide.md#mutating-admission-webh[…]n-a-private-gke-cluster

**Comment by jdonnelly-apixio** [comment]
How many pods are in the namespace? Could it be a legitimate timeout due to there being too many pods to create in whatever the timeout is configured as? I had a similar issue due to configmaps not getting cleaned up.

**Comment by sk-ilya** [comment]
> How many pods are in the namespace? Could it be a legitimate timeout due to there being too many pods to create in whatever the timeout is configured as? I had a similar issue due to configmaps not getting cleaned up.

I faced this issue again, on a different cluster. And yes, it was a legitimate timeout.
Solved by increasing the values of the following:

```
spark.kubernetes.submission.connectionTimeout
spark.kubernetes.submission.requestTimeout
spark.kubernetes.driver.connectionTimeout
spark.kubernetes.driver.requestTimeout
```
