### ISSUE TITLE
RpcOutboxMessage - Ask timeout before connecting successfully when creating ScheduledSparkApplication jobs

### ISSUE THREAD

**Issue by dharmeshkakadia** [GoogleCloudPlatform/spark-on-k8s-operator#146]
I am getting the RPC timeout between driver and executors. The simple ``sparkapplication`` works fine.

Here is the logs from executor pod.

```
	at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:62)
	at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:58)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:216)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Failure.recover(Try.scala:216)
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:326)
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:326)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at org.spark_project.guava.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:293)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$1.execute(ExecutionContextImpl.scala:136)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.Promise$class.complete(Promise.scala:55)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:63)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:78)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:55)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:55)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:54)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:601)
	at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:106)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:599)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.Promise$class.tryFailure(Promise.scala:112)
	at scala.concurrent.impl.Promise$DefaultPromise.tryFailure(Promise.scala:153)
	at org.apache.spark.rpc.netty.NettyRpcEnv.org$apache$spark$rpc$netty$NettyRpcEnv$$onFailure$1(NettyRpcEnv.scala:205)
	at org.apache.spark.rpc.netty.NettyRpcEnv$$anon$1.run(NettyRpcEnv.scala:239)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.TimeoutException: Cannot receive any reply from pyspark-example-1525728618655618581-1525728619985-driver-svc.default.svc.cluster.local:7078 in 120 seconds
	... 8 more
```

The simple sparkapplication works fine:
```yaml
apiVersion: "sparkoperator.k8s.io/v1alpha1"
kind: SparkApplication
metadata:
  name: pyspark-job-example
  namespace: default
spec:
  type: Python
  mode: cluster
  mainApplicationFile: "local:///code/pyspark-example.py"
  Arguments:
  - "wasb://sparkdkakadia@sparkdkakadia.blob.core.windows.net/episodes.avro"
  deps:
    jars:
      - "local:///opt/spark/examples/jars/spark-examples_2.11-2.2.0-k8s-0.5.0.jar" 
  sparkConf:
    "spark.hadoop.fs.azure.account.key.sparkdkakadia.blob.core.windows.net": "4gIguFMiymTI4BoHL2LsbIdEVjDYUZfcgjYqAP6T+/eUXWH9RzJPQAlQpUsT1+hAAsVJdlZd9fBQ+ctZV+I55A=="
  driver:
    cores: 0.5
    image: dharmeshkakadia/spark-py-example:latest
    memory: "2048m"
    labels:
      version: 2.2.0
    serviceAccount: spark
  executor:
    cores: 2
    instances: 2
    image: dharmeshkakadia/spark-executor-py:latest
    memory: "1024m"
    labels:
      version: 2.2.0
  restartPolicy: Never
```

However the same spec does not work under ``ScheduledSparkApplication``.

```yaml
apiVersion: "sparkoperator.k8s.io/v1alpha1"
kind: ScheduledSparkApplication
metadata:
  name: pyspark-example
  namespace: default
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: Replace
  runHistoryLimit: 3
  template:
    type: Python
    mode: cluster
    mainApplicationFile: "local:///code/pyspark-example.py"
    Arguments:
    - "wasb://sparkdkakadia@sparkdkakadia.blob.core.windows.net/episodes.avro"
    deps:
      jars:
        - "local:///opt/spark/examples/jars/spark-examples_2.11-2.2.0-k8s-0.5.0.jar" 
    sparkConf:
      "spark.hadoop.fs.azure.account.key.sparkdkakadia.blob.core.windows.net": "4gIguFMiymTI4BoHL2LsbIdEVjDYUZfcgjYqAP6T+/eUXWH9RzJPQAlQpUsT1+hAAsVJdlZd9fBQ+ctZV+I55A=="
    driver:
      cores: 0.5
      image: dharmeshkakadia/spark-py-example:latest
      memory: "2048m"
      labels:
        version: 2.2.0
      serviceAccount: spark
    executor:
      cores: 2
      instances: 2
      image: dharmeshkakadia/spark-executor-py:latest
      memory: "1024m"
      labels:
        version: 2.2.0
    restartPolicy: Never
```

**Comment by liyinan926** [comment]
Can you run `kubectl describe service pyspark-example-1525728618655618581-1525728619985-driver-svc` or `kubectl get service pyspark-example-1525728618655618581-1525728619985-driver-svc -o=yaml`?

**Comment by dharmeshkakadia** [comment]
Those service were replaced with a newer run. Here is the output from a newer run:

kubectl get service pyspark-example-1525728018523469717-1525728019705-driver-svc -o=yaml
```yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-05-07T21:20:21Z
  name: pyspark-example-1525728018523469717-1525728019705-driver-svc
  namespace: default
  ownerReferences:
  - apiVersion: v1
    controller: true
    kind: Pod
    name: pyspark-example-1525728018523469717-1525728019705-driver
    uid: 72e8b96a-523c-11e8-b0b0-000d3a114aa6
  resourceVersion: "4249048"
  selfLink: /api/v1/namespaces/default/services/pyspark-example-1525728018523469717-1525728019705-driver-svc
  uid: 73113c0f-523c-11e8-b0b0-000d3a114aa6
spec:
  clusterIP: None
  ports:
  - name: driver-rpc-port
    port: 7078
    protocol: TCP
    targetPort: 7078
  - name: blockmanager
    port: 7079
    protocol: TCP
    targetPort: 7079
  selector:
    spark-app-selector: spark-85226883cdf54e2f8ad53a87eac31744
    spark-role: driver
    sparkoperator.k8s.io/app-id: pyspark-example-1525728018523469717-2278518272
    sparkoperator.k8s.io/app-name: pyspark-example-1525728018523469717
    sparkoperator.k8s.io/launched-by-spark-operator: "true"
    version: 2.2.0
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

**Comment by dharmeshkakadia** [comment]
kubectl describe service pyspark-example-1525728018523469717-1525728019705-driver-svc
```
Name:              pyspark-example-1525728018523469717-1525728019705-driver-svc
Namespace:         default
Labels:            <none>
Annotations:       <none>
Selector:          spark-app-selector=spark-85226883cdf54e2f8ad53a87eac31744,spark-role=driver,sparkoperator.k8s.io/app-id=pyspark-example-1525728018523469717-2278518272,sparkoperator.k8s.io/app-name=pyspark-example-1525728018523469717,sparkoperator.k8s.io/launched-by-spark-operator=true,version=2.2.0
Type:              ClusterIP
IP:                None
Port:              driver-rpc-port  7078/TCP
TargetPort:        7078/TCP
Endpoints:         32.0.0.36:7078
Port:              blockmanager  7079/TCP
TargetPort:        7079/TCP
Endpoints:         32.0.0.36:7079
Session Affinity:  None
Events:
  Type     Reason                      Age               From                Message
  ----     ------                      ----              ----                -------
  Warning  CreatingLoadBalancerFailed  1m (x31 over 2h)  service-controller  Error creating load balancer (will retry): error getting LB for service default/pyspark-example-1525728018523469717-1525728019705-driver-svc: Service(default/pyspark-example-1525728018523469717-1525728019705-driver-svc) - Loadbalancer not found
```

**Comment by liyinan926** [comment]
I saw a warning with reason `CreatingLoadBalancerFailed`. I'm not sure if this caused the failure. When you run the same application using a `SparkApplication`, is the same warning observed?

**Comment by dharmeshkakadia** [comment]
Yeah, I don't thing thats related. 

kubectl describe service pyspark-job-example-1525728819227-driver-svc
```
Name:              pyspark-job-example-1525728819227-driver-svc
Namespace:         default
Labels:            <none>
Annotations:       <none>
Selector:          spark-app-selector=spark-d16556138f1a44e09942761ec6b9d0e9,spark-role=driver,sparkoperator.k8s.io/app-id=pyspark-job-example-2346145851,sparkoperator.k8s.io/app-name=pyspark-job-example,sparkoperator.k8s.io/launched-by-spark-operator=true,version=2.2.0
Type:              ClusterIP
IP:                None
Port:              driver-rpc-port  7078/TCP
TargetPort:        7078/TCP
Endpoints:         <none>
Port:              blockmanager  7079/TCP
TargetPort:        7079/TCP
Endpoints:         <none>
Session Affinity:  None
Events:
  Type     Reason                      Age               From                Message
  ----     ------                      ----              ----                -------
  Warning  CreatingLoadBalancerFailed  1m (x30 over 2h)  service-controller  Error creating load balancer (will retry): error getting LB for service default/pyspark-job-example-1525728819227-driver-svc: Service(default/pyspark-job-example-1525728819227-driver-svc) - Loadbalancer not found
```

**Comment by liyinan926** [comment]
What were the labels on the driver pod of the failed run launched using a `ScheduledSparkApplication`?

**Comment by dharmeshkakadia** [comment]
kubectl describe pod/pyspark-example-1525728018523469717-1525728019705-driver
```
Name:         pyspark-example-1525728018523469717-1525728019705-driver
Namespace:    default
Node:         k8s-mdldata-18040746-0/<nil>
Start Time:   Mon, 07 May 2018 14:20:21 -0700
Labels:       spark-app-selector=spark-85226883cdf54e2f8ad53a87eac31744
              spark-role=driver
              sparkoperator.k8s.io/app-id=pyspark-example-1525728018523469717-2278518272
              sparkoperator.k8s.io/app-name=pyspark-example-1525728018523469717
              sparkoperator.k8s.io/launched-by-spark-operator=true
              version=2.2.0
Annotations:  spark-app-name=pyspark-example-1525728018523469717
              sparkoperator.k8s.io/ownerreference=ChBTcGFya0FwcGxpY2F0aW9uGiNweXNwYXJrLWV4YW1wbGUtMTUyNTcyODAxODUyMzQ2OTcxNyIkNzEyZmRmZTEtNTIzYy0xMWU4LWIwYjAtMDAwZDNhMTE0YWE2Kh1zcGFya29wZXJhdG9yLms4cy5pby92MWFscGhh...
Status:       Running
IP:           32.0.0.36
Containers:
  spark-kubernetes-driver:
    Container ID:   docker://77c6369e98a85d1cd26a638c40b57c451c45328f4bb4c7312cc770ba6d7f0728
    Image:          dharmeshkakadia/spark-py-example:latest
    Image ID:       docker-pullable://dharmeshkakadia/spark-py-example@sha256:4c58bccc690fb70c2e0d059e9189a47f3702d0c02a3afe289e93774f87e71442
    Port:           <none>
    State:          Running
      Started:      Mon, 07 May 2018 14:20:26 -0700
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     200m
      memory:  1408Mi
    Requests:
      cpu:     100m
      memory:  1Gi
    Environment:
      SPARK_DRIVER_MEMORY:        1024m
      SPARK_DRIVER_CLASS:         org.apache.spark.deploy.PythonRunner
      SPARK_DRIVER_ARGS:          wasb://sparkdkakadia@sparkdkakadia.blob.core.windows.net/episodes.avro
      SPARK_DRIVER_BIND_ADDRESS:   (v1:status.podIP)
      SPARK_MOUNTED_CLASSPATH:    /opt/spark/examples/jars/spark-examples_2.11-2.2.0-k8s-0.5.0.jar
      PYSPARK_PRIMARY:            /code/pyspark-example.py
      PYSPARK_FILES:              null
      SPARK_JAVA_OPT_0:           -Dspark.kubernetes.driver.pod.name=pyspark-example-1525728018523469717-1525728019705-driver
      SPARK_JAVA_OPT_1:           -Dspark.kubernetes.driver.label.version=2.2.0
      SPARK_JAVA_OPT_2:           -Dspark.submit.deployMode=cluster
      SPARK_JAVA_OPT_3:           -Dspark.jars=/opt/spark/examples/jars/spark-examples_2.11-2.2.0-k8s-0.5.0.jar
      SPARK_JAVA_OPT_4:           -Dspark.kubernetes.authenticate.driver.serviceAccountName=spark
      SPARK_JAVA_OPT_5:           -Dspark.app.name=pyspark-example-1525728018523469717
      SPARK_JAVA_OPT_6:           -Dspark.kubernetes.executor.label.version=2.2.0
      SPARK_JAVA_OPT_7:           -Dspark.hadoop.fs.azure.account.key.sparkdkakadia.blob.core.windows.net=4gIguFMiymTI4BoHL2LsbIdEVjDYUZfcgjYqAP6T+/eUXWH9RzJPQAlQpUsT1+hAAsVJdlZd9fBQ+ctZV+I55A==
      SPARK_JAVA_OPT_8:           -Dspark.kubernetes.driver.limit.cores=200m
      SPARK_JAVA_OPT_9:           -Dspark.kubernetes.executor.docker.image=dharmeshkakadia/spark-executor-py:latest
      SPARK_JAVA_OPT_10:          -Dspark.master=k8s://https://10.0.0.1:443
      SPARK_JAVA_OPT_11:          -Dspark.kubernetes.executor.label.sparkoperator.k8s.io/app-id=pyspark-example-1525728018523469717-2278518272
      SPARK_JAVA_OPT_12:          -Dspark.executor.instances=2
      SPARK_JAVA_OPT_13:          -Dspark.kubernetes.driver.label.sparkoperator.k8s.io/app-id=pyspark-example-1525728018523469717-2278518272
      SPARK_JAVA_OPT_14:          -Dspark.kubernetes.driver.label.sparkoperator.k8s.io/launched-by-spark-operator=true
      SPARK_JAVA_OPT_15:          -Dspark.files=/code/pyspark-example.py
      SPARK_JAVA_OPT_16:          -Dspark.kubernetes.driver.label.sparkoperator.k8s.io/app-name=pyspark-example-1525728018523469717
      SPARK_JAVA_OPT_17:          -Dspark.driver.cores=0.100000
      SPARK_JAVA_OPT_18:          -Dspark.app.id=spark-85226883cdf54e2f8ad53a87eac31744
      SPARK_JAVA_OPT_19:          -Dspark.kubernetes.executor.podNamePrefix=pyspark-example-1525728018523469717-1525728019705
      SPARK_JAVA_OPT_20:          -Dspark.kubernetes.namespace=default
      SPARK_JAVA_OPT_21:          -Dspark.kubernetes.driver.docker.image=dharmeshkakadia/spark-py-example:latest
      SPARK_JAVA_OPT_22:          -Dspark.kubernetes.executor.label.sparkoperator.k8s.io/app-name=pyspark-example-1525728018523469717
      SPARK_JAVA_OPT_23:          -Dspark.driver.blockManager.port=7079
      SPARK_JAVA_OPT_24:          -Dspark.driver.memory=1024m
      SPARK_JAVA_OPT_25:          -Dspark.kubernetes.driver.annotation.sparkoperator.k8s.io/ownerreference=ChBTcGFya0FwcGxpY2F0aW9uGiNweXNwYXJrLWV4YW1wbGUtMTUyNTcyODAxODUyMzQ2OTcxNyIkNzEyZmRmZTEtNTIzYy0xMWU4LWIwYjAtMDAwZDNhMTE0YWE2Kh1zcGFya29wZXJhdG9yLms4cy5pby92MWFscGhhMQ==
      SPARK_JAVA_OPT_26:          -Dspark.driver.port=7078
      SPARK_JAVA_OPT_27:          -Dspark.executor.memory=1024m
      SPARK_JAVA_OPT_28:          -Dspark.kubernetes.executor.label.sparkoperator.k8s.io/launched-by-spark-operator=true
      SPARK_JAVA_OPT_29:          -Dspark.local.dir=/mnt/tmp/spark-local/spark-f0d888cd-9266-410b-aa3d-047eded91c3e
      SPARK_JAVA_OPT_30:          -Dspark.executor.cores=1
      SPARK_JAVA_OPT_31:          -Dspark.driver.host=pyspark-example-1525728018523469717-1525728019705-driver-svc.default.svc.cluster.local
    Mounts:
      /mnt/tmp/spark-local/spark-f0d888cd-9266-410b-aa3d-047eded91c3e from spark-local-dir-0-spark-f0d888cd-9266-410b-aa3d-047eded91c3e (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from spark-token-srgwh (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          True
  PodScheduled   True
Volumes:
  spark-local-dir-0-spark-f0d888cd-9266-410b-aa3d-047eded91c3e:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
  spark-token-srgwh:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  spark-token-srgwh
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     <none>
Events:          <none>
```

**Comment by liyinan926** [comment]
I don't see what could have gone wrong with the service. The label selector of the service matched the labels on the driver pods and the service did show that it had one endpoint. I couldn't figure out why the scheduled runs failed while the non-scheduled run succeeded, given that the `ScheduledSparkApplication` controller just creates a `SparkApplication` instance for each scheduled run. This doesn't look like an issue with the controller itself.

**Comment by dharmeshkakadia** [comment]
My ``kube-dns`` logs are filled with following. Is this expected ?

```
I0506 01:53:50.514010       1 dns.go:555] Could not find endpoints for service "spark-pi-scheduled-1525571626384555486-1525571628502-driver-svc" in namespace "default". DNS records will be created once endpoints show up.
I0506 01:55:09.344492       1 logs.go:41] skydns: failure to forward request "read udp 32.0.0.49:42108->168.63.129.16:53: i/o timeout"
I0506 01:55:11.344741       1 logs.go:41] skydns: failure to forward request "read udp 32.0.0.49:59006->168.63.129.16:53: i/o timeout"
I0506 01:55:11.344809       1 logs.go:41] skydns: failure to forward request "read udp 32.0.0.49:59006->168.63.129.16:53: i/o timeout"
```

**Comment by liyinan926** [comment]
That looks to me like the reason for the failure. But I don't know why if failed with "Could not find endpoints" in the first place.

**Comment by liyinan926** [comment]
Can you run `kubectl describe endpoints <name>`, where `<name>` is the same as the service name for both the services created with a `ScheduledSparkApplication` and a `SparkApplication`?

**Comment by dharmeshkakadia** [comment]
This is related to issue on kube DNS. I am closing it for now.
