### ISSUE TITLE
Error in spark-operator pod when deleting a SparkApplication 

### ISSUE THREAD

**Issue by guptap11** [GoogleCloudPlatform/spark-on-k8s-operator#1467]
The spark-operator pod crashes on deleting a SparkApplication resource using command `kubectl delete SparkApplication <appName>`

Stack trace from the pod logs 
```
E0127 23:30:56.204071       9 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 52 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1679620, 0x241a140)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/runtime/runtime.go:74 +0xa6
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/runtime/runtime.go:48 +0x89
panic(0x1679620, 0x241a140)
	/usr/local/go/src/runtime/panic.go:969 +0x175
github.com/GoogleCloudPlatform/spark-on-k8s-operator/pkg/controller/sparkapplication.(*sparkAppMetrics).exportMetricsOnDelete(0x0, 0xc0003a2000)
	/workspace/pkg/controller/sparkapplication/sparkapp_metrics.go:176 +0x37
github.com/GoogleCloudPlatform/spark-on-k8s-operator/pkg/controller/sparkapplication.(*Controller).handleSparkApplicationDeletion(0xc0004a6090, 0xc0003a2000)
	/workspace/pkg/controller/sparkapplication/controller.go:445 +0x51
github.com/GoogleCloudPlatform/spark-on-k8s-operator/pkg/controller/sparkapplication.(*Controller).onDelete(0xc0004a6090, 0x1832480, 0xc0003a2000)
	/workspace/pkg/controller/sparkapplication/controller.go:238 +0xaa
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnDelete(...)
	/go/pkg/mod/k8s.io/client-go@v0.19.6/tools/cache/controller.go:241
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/go/pkg/mod/k8s.io/client-go@v0.19.6/tools/cache/shared_informer.go:779 +0x166
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00049df60)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0006dbf60, 0x1a1f640, 0xc0004a4780, 0x164a201, 0xc0005c0060)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00049df60, 0x3b9aca00, 0x0, 0x1, 0xc0005c0060)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc0004ce000)
	/go/pkg/mod/k8s.io/client-go@v0.19.6/tools/cache/shared_informer.go:771 +0x95
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0004c6060, 0xc0004aa180)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/wait/wait.go:73 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/wait/wait.go:71 +0x65
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x14e6e97]
```
spark-operator image used `ghcr.io/googlecloudplatform/spark-operator:v1beta2-1.3.2-3.1.1`

**Comment by aneagoe** [comment]
@guptap11 what is the state of the `SparkApplication`? I've tested the same now against `ghcr.io/googlecloudplatform/spark-operator:v1beta2-1.3.3-3.1.1` and I cannot reproduce. Also, is it always happening? Can you try to restart the operator and ensure it's running on a different node to rule out an issue with the node itself?

**Comment by guptap11** [comment]
The SparkApplication is in `completed` state. I have bounced the pod to a different node in the cluster same error. The K8s version of the nodes is `v1.19.13-gke.1200`. Yes it is happening always. It happens if I set TTL and the operator tries to delete the pod result into the same error.

**Comment by guptap11** [comment]
Digging more into it. The error seems to be coming from this section of code 
https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/pkg/controller/sparkapplication/sparkapp_metrics.go#L176
The operator was running without the metrics enabled `-enable-metrics` flag was not set and on deleting the `SparkApplication` it runs into error. 
While running with `-enable-metrics=true` there was no error. It seems we need to put a check to only call the function when the flag is enabled.

**Comment by aneagoe** [comment]
@guptap11 thanks for taking the time to investigate this further. Indeed, your suggestion is reasonable. Have you tested a build with this in place? Would you have the time to submit a PR with this fix?

**Comment by guptap11** [comment]
@aneagoe Sorry I haven't tested the build with the change. I will try to work on it and submit a PR.
