### ISSUE TITLE
network policies - failed to create the spark driver

### ISSUE THREAD

**Issue by SBatais** [GoogleCloudPlatform/spark-on-k8s-operator#1532]
Hello

Spark operator version: v1beta2-1.3.3-3.1.2

I'm trying to implement kubernetes network policies on a namespace where the spark-operator is deployed, and I'm encountering some issues.
When allowing only the ingress traffic inside the namespace, and when I create a sparkApplication, the spark-operator contoler receives the event, but the spark driver is not created and I get the below error.
When all ingress traffic is allowed, there's no problem.

```
Exception in thread "main" io.fabric8.kubernetes.client.KubernetesClientException: Operation: [create]  for kind: [Pod]  with name: [null]  in namespace: [p99999]  failed.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:72)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:349)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:84)
	at org.apache.spark.deploy.k8s.submit.Client.run(KubernetesClientApplication.scala:139)
	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.$anonfun$run$3(KubernetesClientApplication.scala:213)
	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.$anonfun$run$3$adapted(KubernetesClientApplication.scala:207)
	at org.apache.spark.util.Utils$.tryWithResource(Utils.scala:2622)
	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.run(KubernetesClientApplication.scala:207)
	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.start(KubernetesClientApplication.scala:179)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:951)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1039)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1048)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.net.SocketTimeoutException: timeout 
```
Any ideas ?
Thanks in advance

**Comment by SBatais** [comment]
I think that the solution is to add a network policy, as described below, that allow the ingress traffic to webhook.port
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
spec:
...
  policyTypes:
  - Ingress
  ingress:
# allow traffic to webhook port
  - from:
    ports:
      - port: <webhook.port>
```
