### ISSUE TITLE
Unable to reproduce developer guide instructions

### ISSUE THREAD

**Issue by tahesse** [GoogleCloudPlatform/spark-on-k8s-operator#1536]
I just tried to follow https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/developer-guide.md and I ran into issues.

# Steps to reproduce:
(constantly working with the same shell)

1. Setup Go 1.15 locally
```console 
$ # download go1.15 from https://go.dev/dl/
$ wget https://go.dev/dl/go1.15.15.linux-amd64.tar.gz ~
$ tar xfz go1.15.15.linux-amd64.tar.gz
# mkdir -p /opt/go && mv go /opt/go/1.15.15
$ GOROOT=/opt/go/1.15.15
$ GO111MODULE=on
```

2. Clone repository (from `developer-guide.md`)
```console
$ mkdir -p $GOPATH/src/github.com/GoogleCloudPlatform
$ cd $GOPATH/src/github.com/GoogleCloudPlatform
$ git clone git@github.com:GoogleCloudPlatform/spark-on-k8s-operator.git
$ cd spark-on-k8s-operator
```

3. Install module dependencies
```console
$ mkdir .go
$ GOPATH=/path/to/spark-on-k8s-operator/.go
$ go mod download
```

When I now run `hack/update-codegen.sh` I receive the following output:
```console
Generating deepcopy funcs
F0524 12:23:52.542689   73029 main.go:82] Error: Failed executing generator: some packages had errors:
errors in package "github.com/GoogleCloudPlatform/spark-on-k8s-operator/pkg/apis/sparkoperator.k8s.io/v1beta1":
open ../../../github.com/GoogleCloudPlatform/spark-on-k8s-operator/pkg/apis/sparkoperator.k8s.io/v1beta1/zz_generated.deepcopy.go: no such file or directory

errors in package "github.com/GoogleCloudPlatform/spark-on-k8s-operator/pkg/apis/sparkoperator.k8s.io/v1beta2":
open ../../../github.com/GoogleCloudPlatform/spark-on-k8s-operator/pkg/apis/sparkoperator.k8s.io/v1beta2/zz_generated.deepcopy.go: no such file or directory

goroutine 1 [running]:
k8s.io/klog/v2.stacks(0xc000010001, 0xc00b0ce000, 0x283, 0x2d9)
        /home/io/Code/spark-on-k8s-operator/.go/pkg/mod/k8s.io/klog/v2@v2.2.0/klog.go:996 +0xb9
k8s.io/klog/v2.(*loggingT).output(0x9a58c0, 0xc000000003, 0x0, 0x0, 0xc00b0c6000, 0x97de8f, 0x7, 0x52, 0x0)
        /home/io/Code/spark-on-k8s-operator/.go/pkg/mod/k8s.io/klog/v2@v2.2.0/klog.go:945 +0x191
k8s.io/klog/v2.(*loggingT).printf(0x9a58c0, 0xc000000003, 0x0, 0x0, 0x76e216, 0x9, 0xc00a391df8, 0x1, 0x1)
        /home/io/Code/spark-on-k8s-operator/.go/pkg/mod/k8s.io/klog/v2@v2.2.0/klog.go:733 +0x17a
k8s.io/klog/v2.Fatalf(...)
        /home/io/Code/spark-on-k8s-operator/.go/pkg/mod/k8s.io/klog/v2@v2.2.0/klog.go:1456
main.main()
        /home/io/Code/spark-on-k8s-operator/.go/pkg/mod/k8s.io/code-generator@v0.19.6/cmd/deepcopy-gen/main.go:82 +0x505

goroutine 6 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x9a58c0)
        /home/io/Code/spark-on-k8s-operator/.go/pkg/mod/k8s.io/klog/v2@v2.2.0/klog.go:1131 +0x8b
created by k8s.io/klog/v2.init.0
        /home/io/Code/spark-on-k8s-operator/.go/pkg/mod/k8s.io/klog/v2@v2.2.0/klog.go:416 +0xd8
```

The `zz_generated.deepcopy.go` exists but I think that the path is off. Any ideas?

**Comment by tahesse** [comment]
Changing the conflicting line at https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/hack/update-codegen.sh#L31 to 
```go
  --output-base "$(dirname ${BASH_SOURCE})/../../.."
```
solved my issue.
