### ISSUE TITLE
If both hadoopConfigMap and sparkConfigMap are specified, spark operator does not create driver

### ISSUE THREAD

**Issue by mrow4a** [GoogleCloudPlatform/spark-on-k8s-operator#165]
I noticed that whenever both hadoopConfigMap and sparkConfigMap are specified, there is an exception raised 

However, if I specify them alone, it works e.g. 

```
apiVersion: "sparkoperator.k8s.io/v1alpha1"
kind: SparkApplication
metadata:
  name: secure-eos-events-select
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: "gitlab-registry.cern.ch/db/spark-service/docker-registry/spark-on-k8s:v2.3.0-xrootd-s3"
  imagePullPolicy: Always
  mainClass: org.sparkservice.sparkrootapplications.examples.EventsSelect
  mainApplicationFile: "local:///opt/spark/examples/jars/spark-service-examples_2.11-0.0.1.jar"
  arguments:
    - "root://eosuser.cern.ch/eos/user/p/pmrowczy/Downloads/evsel.root"
  deps:
    jars:
      - http://central.maven.org/maven2/org/diana-hep/root4j/0.1.6/root4j-0.1.6.jar
      - http://central.maven.org/maven2/org/apache/bcel/bcel/5.2/bcel-5.2.jar
      - http://central.maven.org/maven2/org/diana-hep/spark-root_2.11/0.1.16/spark-root_2.11-0.1.16.jar
  #hadoopConfigMap: secure-eos-events-select-hadoop-conf #<- does not work with sparkConfigMap
  sparkConfigMap: secure-eos-events-select-spark-conf #<- does not work with hadoopConfigMap
  sparkConf:
    "spark.kubernetes.driverEnv.KRB5CCNAME": /usr/lib/hadoop/etc/hadoop/krb5cc_0
    "spark.executorEnv.KRB5CCNAME": /usr/lib/hadoop/etc/hadoop/krb5cc_0
#    "spark.kubernetes.driverEnv.KRB5CCNAME": /etc/hadoop/conf/krb5cc_0
#    "spark.executorEnv.KRB5CCNAME": /etc/hadoop/conf/krb5cc_0
  driver:
    cores: 1
    coreLimit: "1000m"
    memory: "1024m"
    labels:
      version: 2.3.0
    serviceAccount: spark
    configMaps:
      - name: secure-eos-events-select-hadoop-conf #<- does work
        path: /usr/lib/hadoop/etc/hadoop/
#    configMaps:
#      - name: secure-eos-events-select-spark-conf #<- does work
#        path: /opt/spark/conf
  executor:
    instances: 1
    cores: 2
    memory: "2048m"
    labels:
      version: 2.3.0
    configMaps:
      - name: secure-eos-events-select-hadoop-conf #<- does work
        path: /usr/lib/hadoop/etc/hadoop/
#    configMaps:
#      - name: secure-eos-events-select-spark-conf  #<- does work
#        path: /opt/spark/conf
  restartPolicy: Never
```

Below there is an exception raised

```
Name:         secure-eos-events-select
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  sparkoperator.k8s.io/v1alpha1
Kind:         SparkApplication
Metadata:
  Cluster Name:
  Creation Timestamp:  2018-05-24T13:51:57Z
  Generation:          1
  Resource Version:    104967
  Self Link:           /apis/sparkoperator.k8s.io/v1alpha1/namespaces/default/sparkapplications/secure-eos-events-select
  UID:                 a028cf32-5f59-11e8-a690-02163e01c159
Spec:
  Arguments:
    root://eosuser.cern.ch/eos/user/p/pmrowczy/Downloads/evsel.root
  Deps:
    Jars:
      http://central.maven.org/maven2/org/diana-hep/root4j/0.1.6/root4j-0.1.6.jar
      http://central.maven.org/maven2/org/apache/bcel/bcel/5.2/bcel-5.2.jar
      http://central.maven.org/maven2/org/diana-hep/spark-root_2.11/0.1.16/spark-root_2.11-0.1.16.jar
  Driver:
    Core Limit:  1000m
    Cores:       1
    Labels:
      Version:        2.3.0
    Memory:           1024m
    Service Account:  spark
  Executor:
    Cores:      2
    Instances:  1
    Labels:
      Version:            2.3.0
    Memory:               2048m
  Hadoop Config Map:      secure-eos-events-select-hadoop-conf
  Image:                  gitlab-registry.cern.ch/db/spark-service/docker-registry/spark-on-k8s:v2.3.0-xrootd-s3
  Image Pull Policy:      Always
  Main Application File:  local:///opt/spark/examples/jars/spark-service-examples_2.11-0.0.1.jar
  Main Class:             org.sparkservice.sparkrootapplications.examples.EventsSelect
  Mode:                   cluster
  Restart Policy:         Never
  Spark Config Map:       secure-eos-events-select-spark-conf
  Type:                   Scala
Status:
  App Id:  secure-eos-events-select-4075353935
  Application State:
    Error Message:  Exception in thread "main" io.fabric8.kubernetes.client.KubernetesClientException: Operation: [create]  for kind: [Pod]  with name: [null]  in namespace: [default]  failed.
                    at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:62)
                    at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:71)
                    at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:363)
                    at org.apache.spark.deploy.k8s.submit.Client$$anonfun$run$3.apply(KubernetesClientApplication.scala:145)
                    at org.apache.spark.deploy.k8s.submit.Client$$anonfun$run$3.apply(KubernetesClientApplication.scala:144)
                    at org.apache.spark.util.Utils$.tryWithResource(Utils.scala:2585)
                    at org.apache.spark.deploy.k8s.submit.Client.run(KubernetesClientApplication.scala:144)
                    at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication$$anonfun$run$5.apply(KubernetesClientApplication.scala:235)
                    at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication$$anonfun$run$5.apply(KubernetesClientApplication.scala:227)
                    at org.apache.spark.util.Utils$.tryWithResource(Utils.scala:2585)
                    at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.run(KubernetesClientApplication.scala:227)
                    at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.start(KubernetesClientApplication.scala:192)
                    at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:879)
                    at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:197)
                    at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:227)
                    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:136)
                    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.net.SocketTimeoutException: timeout
  at okio.Okio$4.newTimeoutException(Okio.java:230)
  at okio.AsyncTimeout.exit(AsyncTimeout.java:285)
  at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
  at okio.RealBufferedSource.indexOf(RealBufferedSource.java:345)
  at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217)
  at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:211)
  at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
  at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:75)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
  at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
  at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
  at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
  at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
  at io.fabric8.kubernetes.client.utils.HttpClientUtils$2.intercept(HttpClientUtils.java:93)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
  at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
  at okhttp3.RealCall.execute(RealCall.java:69)
  at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:377)
  at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:343)
  at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:226)
  at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:769)
  at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:356)
  ... 14 more
Caused by: java.net.SocketException: Socket closed
  at java.net.SocketInputStream.read(SocketInputStream.java:204)
  at java.net.SocketInputStream.read(SocketInputStream.java:141)
  at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
  at sun.security.ssl.InputRecord.read(InputRecord.java:503)
  at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
  at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
  at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
  at okio.Okio$2.read(Okio.java:139)
  at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
  ... 41 more

    State:          SUBMISSION_FAILED
  Completion Time:  <nil>
  Driver Info:
    Web UI Port:          30289
    Web UI Service Name:  secure-eos-events-select-4075353935-ui-svc
  Submission Time:        2018-05-24T13:51:57Z
Events:
  Type     Reason                            Age   From            Message
  ----     ------                            ----  ----            -------
  Normal   SparkApplicationAdded             17s   spark-operator  SparkApplication secure-eos-events-select was added, enqueued it for submission
  Warning  SparkApplicationSubmissionFailed  3s    spark-operator  SparkApplication secure-eos-events-select failed submission: Exception in thread "main" io.fabric8.kubernetes.client.KubernetesClientException: Operation: [create]  for kind: [Pod]  with name: [null]  in namespace: [default]  failed.
```

**Comment by mrow4a** [comment]
Any hints on how to fix it?

**Comment by mrow4a** [comment]
These are logs of api server `journalctl -fu kube-apiserver`

```
May 24 14:16:31 kube-alpha-test-doxdwjyb6nfd-master-0.cern.ch runc[3949]: E0524 14:16:31.096228       1 status.go:64] apiserver received an error that is not an metav1.Status: The order in patch list:
May 24 14:16:31 kube-alpha-test-doxdwjyb6nfd-master-0.cern.ch runc[3949]: [map[name:SPARK_CONF_DIR value:/etc/spark/conf] map[name:SPARK_CLASSPATH value:/etc/hadoop/conf:$SPARK_CLASSPATH] map[name:SPARK_CLASSPATH value:/etc/spark/conf:$SPARK_CLASSPATH] map[name:HADOOP_CONF_DIR value:/etc/hadoop/conf]]
May 24 14:16:31 kube-alpha-test-doxdwjyb6nfd-master-0.cern.ch runc[3949]:  doesn't match $setElementOrder list:
May 24 14:16:31 kube-alpha-test-doxdwjyb6nfd-master-0.cern.ch runc[3949]: [map[name:KRB5CCNAME] map[name:SPARK_DRIVER_MEMORY] map[name:SPARK_DRIVER_CLASS] map[name:SPARK_DRIVER_ARGS] map[name:SPARK_DRIVER_BIND_ADDRESS] map[name:SPARK_MOUNTED_CLASSPATH] map[name:SPARK_MOUNTED_FILES_DIR] map[name:SPARK_JAVA_OPT_0] map[name:SPARK_JAVA_OPT_1] map[name:SPARK_JAVA_OPT_2] map[name:SPARK_JAVA_OPT_3] map[name:SPARK_JAVA_OPT_4] map[name:SPARK_JAVA_OPT_5] map[name:SPARK_JAVA_OPT_6] map[name:SPARK_JAVA_OPT_7] map[name:SPARK_JAVA_OPT_8] map[name:SPARK_JAVA_OPT_9] map[name:SPARK_JAVA_OPT_10] map[name:SPARK_JAVA_OPT_11] map[name:SPARK_JAVA_OPT_12] map[name:SPARK_JAVA_OPT_13] map[name:SPARK_JAVA_OPT_14] map[name:SPARK_JAVA_OPT_15] map[name:SPARK_JAVA_OPT_16] map[name:SPARK_JAVA_OPT_17] map[name:SPARK_JAVA_OPT_18] map[name:SPARK_JAVA_OPT_19] map[name:SPARK_JAVA_OPT_20] map[name:SPARK_JAVA_OPT_21] map[name:SPARK_JAVA_OPT_22] map[name:SPARK_JAVA_OPT_23] map[name:SPARK_JAVA_OPT_24] map[name:SPARK_JAVA_OPT_25] map[name:SPARK_JAVA_OPT_26] map[name:SPARK_JAVA_OPT_27] map[name:SPARK_JAVA_OPT_28] map[name:SPARK_JAVA_OPT_29] map[name:SPARK_JAVA_OPT_30] map[name:SPARK_JAVA_OPT_31] map[name:SPARK_JAVA_OPT_32] map[name:SPARK_JAVA_OPT_33] map[name:SPARK_JAVA_OPT_34] map[name:SPARK_JAVA_OPT_35] map[name:SPARK_JAVA_OPT_36] map[name:SPARK_CONF_DIR] map[name:SPARK_CLASSPATH] map[name:HADOOP_CONF_DIR] map[name:SPARK_CLASSPATH]]
```

**Comment by liyinan926** [comment]
Looking into this.

**Comment by liyinan926** [comment]
It looks like a bug. I think the problem is with the environment variable `SPARK_CLASSPATH`. It's set for both `sparkConfigMap` and `hadoopConfigMap` in the form `$SPARK_CONF_DIR:$SPARK_CLASSPATH` and `$HADOOP_CONF_DIR:$SPARK_CLASSPATH`, respectively. The two are conflicting with each other.

**Comment by mrow4a** [comment]
Hmm, let me try - I might have an idea

**Comment by mrow4a** [comment]
Fix here: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/170
