### ISSUE TITLE
How to call this from Python script?

### ISSUE THREAD

**Issue by j-adamczyk** [GoogleCloudPlatform/spark-on-k8s-operator#1677]
I wanted to call this operator from a Python script programmatically via the official Kubernetes client for Python, like this:
```
from kubernetes import client, config
from kubernetes.utils import create_from_yaml

config.load_kube_config()
k8s_client = client.ApiClient()
yaml_file = "spark-pi-config.yml"
create_from_yaml(k8s_client, yaml_file, namespace="spark-operator")
```

However, I get an error:
```
Traceback (most recent call last):
  File "/home/jakub/PycharmProjects/abp/tmp_launch_job.py", line 7, in <module>
    create_from_yaml(k8s_client, yaml_file, namespace="spark-operator")
  File "/home/jakub/.cache/pypoetry/virtualenvs/abp-SKN_ogPD-py3.10/lib/python3.10/site-packages/kubernetes/utils/create_from_yaml.py", line 162, in create_from_yaml
    return create_with(yml_document_all)
  File "/home/jakub/.cache/pypoetry/virtualenvs/abp-SKN_ogPD-py3.10/lib/python3.10/site-packages/kubernetes/utils/create_from_yaml.py", line 146, in create_with
    created = create_from_dict(k8s_client, yml_document, verbose,
  File "/home/jakub/.cache/pypoetry/virtualenvs/abp-SKN_ogPD-py3.10/lib/python3.10/site-packages/kubernetes/utils/create_from_yaml.py", line 216, in create_from_dict
    created = create_from_yaml_single_item(
  File "/home/jakub/.cache/pypoetry/virtualenvs/abp-SKN_ogPD-py3.10/lib/python3.10/site-packages/kubernetes/utils/create_from_yaml.py", line 242, in create_from_yaml_single_item
    k8s_api = getattr(client, fcn_to_call)(k8s_client)
AttributeError: module 'kubernetes.client' has no attribute 'SparkoperatorV1beta2Api'

Process finished with exit code 1
```

How can I do this? Or should I use another client, or just always use the CLI?

**Comment by AlexNavara** [comment]
I guess you should find out how to make your client work with custom resources. It fails because it doesn't know what is 'SparkApplication' out of the box. Probably this is what you're looking for: https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CustomObjectsApi.md

**Comment by j-adamczyk** [comment]
Thanks @AlexNavara, the key is that `kubernetes` library uses CustomObjectsApi for this operator. So the code is something like:
```
k8s_api_client = ApiClient(k8s_config)
k8s_spark_api_client = CustomObjectsApi(k8s_api_client)
k8s_spark_properties = dict(
    group="sparkoperator.k8s.io",
    version="v1beta2",
    plural="sparkapplications",
     namespace=namespace,
)

# load job YAML to application_config variable

k8s_spark_api_client.create_namespaced_custom_object(
    body=application_config, **k8s_spark_properties
)
```
