### ISSUE TITLE
Can't publish messages from spark operator to PubSub

### ISSUE THREAD

**Issue by yasseraj** [GoogleCloudPlatform/spark-on-k8s-operator#1713]
When I try to publish a PubSub message from a container using the image version _gcr.io/spark-operator/spark-py:v3.1.1_, if I run the same code on my local machine the message is published successfully.
I tested with these versions 2.13.12,  2.15.2 and 2.2.0 of google-cloud-pubsub, and nothing, I get the following error.

`Traceback (most recent call last):
  File "/app/sparkjob.py", line 200, in <module>
    pubsub_helper.get_publisher(PUB_ID).publish_event_from_json(event.data, event.get_attributes_map())
  File "/usr/local/lib/python3.7/dist-packages/xriba/pubsub/publisher.py", line 69, in publish_event_from_json
    self.publish_event(json.dumps(json_data), attributes, publish_callback)
  File "/usr/local/lib/python3.7/dist-packages/xriba/pubsub/publisher.py", line 56, in publish_event
    future = self.__pubsub_publisher.publish(self.__topic_path, data=data_to_send, **attributes)
  File "/usr/local/lib/python3.7/dist-packages/google/cloud/pubsub_v1/publisher/client.py", line 359, in publish
    # should be constructed by directly using the raw protobuf class, and only
TypeError: All attributes being published to Pub/Sub must be sent as text strings.`

The content of event.data (dict that is converted into a json string using json.dumps, see the call trace) and event.get_attributes_map() (dict) is the following, and you can see it's all strings:
```
print(event.get_attributes_map())
{'event_type': 'IMEX',
 'project_id': 'project-nine',
 'data_version': '1.0.0',
 'meta_data_version': '1.0.0',
 'trace': 'dee5773e-bf74-4c43-93d7-48685r80109d',
 'content_type': 'application/json'}

print(event.data)
{'TEAM': 'DATA_ENGINEERING',
 'bucket': 'gcs_test',
 'table_name': 'clients',
 'export_id': 'e653b134-35f0-43ac-a457-9f400000011'}
print(json.dumps(event.data))
'{"TEAM": "DATA_ENGINEERING", "bucket": "gcs_test", "table_name": "clients", "export_id": "e653b134-35f0-43ac-a457-9f400000011"}'
```

**Comment by yasseraj** [comment]
I solved it by calling directly the publish function without passing by the custom code, probably something is changing the data in the middle.
