### ISSUE TITLE
Unable to launch executor pod with PVs

### ISSUE THREAD

**Issue by krisnaru** [GoogleCloudPlatform/spark-on-k8s-operator#1774]
Followed Spark users guide https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/user-guide.md and enabled PVs and ran into errors for the latest spark image.
`
FROM docker-dev.artifactory.tools.roku.com/apache/spark:3.3.1
RUN curl https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.1/hadoop-aws-3.3.1.jar --output /opt/spark/jars/hadoop-aws-3.3.1.jar

RUN curl https://repo1.maven.org/maven2/com/google/cloud/bigdataoss/gcs-connector/hadoop3-2.2.15/gcs-connector-hadoop3-2.2.15.jar --output /opt/spark/jars/gcs-connector-hadoop3-2.2.15.jar

RUN curl https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.486/aws-java-sdk-bundle-1.12.486.jar --output /opt/spark/jars/aws-java-sdk-bundle-1.12.486.jar 
RUN mkdir /tmp/data
RUN chmod -R 777 /tmp/data
RUN chown -R 185:root /tmp/data

CMD ["/bin/bash"]
`

Spec:
    spark.kubernetes.executor.volumes. persistentVolumeClaim.spark-local-dir-1.options.claimName: "OnDemand"
    spark.kubernetes.executor.volumes.persistentVolumeClaim.spark-local-dir-1.options.storageClass: "rokumesh-ebs-csi-gp3"
    spark.kubernetes.executor.volumes.persistentVolumeClaim.spark-local-dir-1.options.sizeLimit: "100Gi"
    spark.kubernetes.executor.volumes.persistentVolumeClaim.spark-local-dir-1.mount.path: "/tmp/data"
    spark.kubernetes.executor.volumes.persistentVolumeClaim.spark-local-dir-1.mount.readOnly: "false"

Exception:
23/06/11 05:08:35 ERROR DiskBlockManager: Failed to create local dir in /tmp/data. Ignoring this directory.
java.io.IOException: Failed to create a temp directory (under /tmp/data) after 10 attempts!
	at org.apache.spark.network.util.JavaUtils.createDirectory(JavaUtils.java:391)
	at org.apache.spark.util.Utils$.createDirectory(Utils.scala:323)
	at org.apache.spark.storage.DiskBlockManager.$anonfun$createLocalDirs$1(DiskBlockManager.scala:252)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:293)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:293)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:290)
	at scala.collection.mutable.ArrayOps$ofRef.flatMap(ArrayOps.scala:198)
	at org.apache.spark.storage.DiskBlockManager.createLocalDirs(DiskBlockManager.scala:250)
	at org.apache.spark.storage.DiskBlockManager.<init>(DiskBlockManager.scala:60)
	at org.apache.spark.storage.BlockManager.<init>(BlockManager.scala:200)
	at org.apache.spark.SparkEnv$.create(SparkEnv.scala:381)

**Comment by krisnaru** [comment]
I am using opensource image: https://hub.docker.com/layers/apache/spark/3.4.0/images/sha256-09939a7b06f64dca0a35d02a13573702815e6ffab53ce1be6ec14c8c3d13aa22?context=explore

which does not have groupId defined.

**Comment by krisnaru** [comment]
i am running as non root user: spark. 
`    Environment:
      SPARK_USER:                   spark
`

**Comment by krisnaru** [comment]
Actually adding this worked. thank you @julienlau ` 
 executor:
    podSecurityContext:
      fsGroup: 185
`

**Comment by ousmaneTra** [comment]
And make sure to enable webhook in the operator (also set webhook port to 443 in secured environnement) in addition to executor: podSecurityContext: fsGroup: 185.
I just spent a day trying make that work in EKS 😄
