### ISSUE TITLE
Volume is not mounted into custom object

### ISSUE THREAD

**Issue by roksolana-d** [GoogleCloudPlatform/spark-on-k8s-operator#393]
I would like to mount the application jar file as a volume and use it from this volume in the Spark application definition, however, when I try to do that I get an error:

```
2019-02-07 08:42:06 WARN  DependencyUtils:66 - Local jar /tmp/spark_app_example_log4j.jar does not exist, skipping.
2019-02-07 08:42:06 WARN  SparkSubmit$$anon$2:87 - Failed to load example.SparkAppExample.
java.lang.ClassNotFoundException: example.SparkAppExample
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.spark.util.Utils$.classForName(Utils.scala:238)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:807)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:194)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:921)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:932)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

The jar file is in the http_server directory which is a hostPath volume and the class is located in jar file as well, so I guess, it is some permissions problem as the data is not mounted into the container itself, I tested other (not Spark) containers and the data is mounted without any problems.
I enabled an operator with webhooks (`kubectl apply -f manifest/spark-operator-with-webhook.yaml`) as I build my own Spark operator, but an error does not disappear. What could be wrong with permissions?

Spark application definition looks like this:

```
apiVersion: sparkoperator.k8s.io/v1alpha1
kind: SparkApplication
metadata:
  name: spark-example
  namespace: default
spec:
  type: Scala
  image: gcr.io/ynli-k8s/spark:v2.4.0-SNAPSHOT
  mainClass: example.SparkAppExample
  mainApplicationFile: local:///tmp/spark_app_example_log4j.jar
  mode: cluster
  arguments:
    - "k8s://https://192.168.99.100:8443"
  volumes:
    - name: jar-pv-storage
      hostPath:
        path: /http_server
        type: Directory
  driver:
    coreLimit: 1000m
    cores: 0.1
    labels:
      version: 2.4.0
    memory: 1024m
    serviceAccount: default
    volumeMounts:
      - name: jar-pv-storage
        mountPath: /tmp
  executor:
    cores: 1
    instances: 1
    labels:
      version: 2.4.0
    memory: 1024m
    volumeMounts:
      - name: jar-pv-storage
        mountPath: /tmp
  imagePullPolicy: Always
```

**Comment by roksolana-d** [comment]
I did not notice how defined the wrong host Path directory
