### ISSUE TITLE
Job is not submited if driver pod name exceeds 63 characters

### ISSUE THREAD

**Issue by amukhopad** [GoogleCloudPlatform/spark-on-k8s-operator#459]
Submitting job with name that exceeds 43 symbols leads to `spark-submit` error inside spark-operator. 

```
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://10.3.240.1/api/v1/namespaces/internaltenant/pods. Message: Pod "dbojaitestjavaapi-saveandloaddbdftest-driver" is invalid: metadata.labels: Invalid value: "dbojaitestjavaapi-saveandloaddbdftest-1553778202847818543": must be no more than 63 characters. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=metadata.labels, message=Invalid value: "dbojaitestjavaapi-saveandloaddbdftest-1553778202847818543": must be no more than 63 characters, reason=FieldValueInvalid, additionalProperties={})], group=null, kind=Pod, name=dbojaitestjavaapi-saveandloaddbdftest-driver, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Pod "dbojaitestjavaapi-saveandloaddbdftest-driver" is invalid: metadata.labels: Invalid value: "dbojaitestjavaapi-saveandloaddbdftest-1553778202847818543": must be no more than 63 characters, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:470)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:409)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:379)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:343)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:226)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:769)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:356)
	at org.apache.spark.deploy.k8s.submit.Client$$anonfun$run$2.apply(KubernetesClientApplication.scala:141)
	at org.apache.spark.deploy.k8s.submit.Client$$anonfun$run$2.apply(KubernetesClientApplication.scala:140)
	at org.apache.spark.util.Utils$.tryWithResource(Utils.scala:2567)
```

As proposal I suggest to limit `meta.name` in `CustomResourceDefinition` to 40 characters to fail submission of `SparkApplication` early.

**Comment by liyinan926** [comment]
It's not that the pod name violates the limit, it's the value of one of the labels. Looks like the problematic label is `sparkoperator.k8s.io/submission-id`.

**Comment by amukhopad** [comment]
@liyinan926 But it copies application name, doesnt it?

**Comment by liyinan926** [comment]
Yes, it uses the application name as prefix. Actually I don't think it's really necessary to include the application name in that label as there's already a label for the application name.

**Comment by liyinan926** [comment]
PR https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/462 changed the submission id to use a UUID, which less than 63 characters long.

**Comment by amukhopad** [comment]
@liyinan926 Issue still exists. I guess, now those labels are the problem 
```
--conf spark.kubernetes.driver.label.sparkoperator.k8s.io/app-name
--conf spark.kubernetes.executor.label.sparkoperator.k8s.io/app-name
```
when I remove them, job starts with long name.
