### ISSUE TITLE
Spark operator generates timeout issues during pod creating after job execution on GKE

### ISSUE THREAD

**Issue by zwennesm** [GoogleCloudPlatform/spark-on-k8s-operator#537]
**Summary**
The Spark operator generates timeout issues during pod creating after job execution on a GKE cluster (1.12.7-gke.24).

**Steps to reproduce**
Install the operator
```
helm install incubator/sparkoperator --namespace spark --name spark-operator --set sparkJobNamespace=spark --set enable-metrics=true --set enableWebhook=true
```
Run a job containing a volume
```
apiVersion: "sparkoperator.k8s.io/v1beta1"
kind: SparkApplication
metadata:
  name: {{ item.name }}
  namespace: spark
spec:
  type: Scala
  mode: cluster
  image: "gcr.io/spark-operator/spark:v2.4.0-gcs-prometheus"
  imagePullPolicy: Always
  mainClass: nl.debijenkorf.core.SparkApplication
  mainApplicationFile: "gs://BUCKET/APPLICATION.jar"
  sparkVersion: "2.4.0"
  arguments: 
    - {{ item.job }}
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/spark/data"
        type: Directory  
  driver:
    {..}
  executor:
    {..}
```

**Actual results**
```
I0702 08:24:10.298358      11 controller.go:522] Trying to update SparkApplication spark/test-volume-claim, from: [{  2019-07-02 07:26:25 +0000 UTC 0001-01-01 00:00:00 +0000 UTC { 0    } {FAILED failed to run spark-submit for SparkApplication spark/test-volume-claim: Exception in thread "main" io.fabric8.kubernetes.client.KubernetesClientException: Operation: [create]  for kind: [Pod]  with name: [null]  in namespace: [spark]  failed.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:62)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:71)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:363)
	at org.apache.spark.deploy.k8s.submit.Client$$anonfun$run$2.apply(KubernetesClientApplication.scala:141)
	at org.apache.spark.deploy.k8s.submit.Client$$anonfun$run$2.apply(KubernetesClientApplication.scala:140)
	at org.apache.spark.util.Utils$.tryWithResource(Utils.scala:2543)
	at org.apache.spark.deploy.k8s.submit.Client.run(KubernetesClientApplication.scala:140)
	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication$$anonfun$run$5.apply(KubernetesClientApplication.scala:250)
	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication$$anonfun$run$5.apply(KubernetesClientApplication.scala:241)
	at org.apache.spark.util.Utils$.tryWithResource(Utils.scala:2543)
	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.run(KubernetesClientApplication.scala:241)
	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.start(KubernetesClientApplication.scala:204)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:849)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.net.SocketTimeoutException: timeout
	at okio.Okio$4.newTimeoutException(Okio.java:230)
	at okio.AsyncTimeout.exit(AsyncTimeout.java:285)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:345)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:211)
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:75)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at io.fabric8.kubernetes.client.utils.HttpClientUtils$2.intercept(HttpClientUtils.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
	at okhttp3.RealCall.execute(RealCall.java:69)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:377)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:343)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:226)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:769)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:356)
	... 16 more
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketInputStream.read(SocketInputStream.java:204)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	... 43 more
```

The mutating webhook seems to be there:
```
➜ kubectl get MutatingWebhookConfiguration
NAME                                          CREATED AT
spark-operator-sparkoperator-webhook-config   2019-07-02T07:24:40Z
```
Same aplies to the service:
```
➜ kgs -n spark
NAME                     TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)   AGE
spark-operator-webhook   ClusterIP   10.249.0.99   <none>        443/TCP   67m
```

Anyone has an idea what could be the issue?

**Comment by doctapp** [comment]
Same problem on GKE for me, works fine on our bare metal Kubernetes though.

**Comment by liyinan926** [comment]
Interesting. Will try to reproduce it when I get back to work next week.

**Comment by doctapp** [comment]
Can reproduce it using spark-pi example:
```
apiVersion: "sparkoperator.k8s.io/v1beta1"
kind: SparkApplication
metadata:
  name: spark-pi
  namespace: spark-operator
spec:
  type: Scala
  mode: cluster
  image: "gcr.io/spark-operator/spark:v2.4.0"
  imagePullPolicy: Always
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///opt/spark/examples/jars/spark-examples_2.11-2.4.0.jar"
  sparkVersion: "2.4.0"
  restartPolicy:
    type: Never
  volumes:
  - name: "test-volume"
    hostPath:
      path: "/tmp"
      type: Directory
  driver:
    cores: 0.1
    coreLimit: "200m"
    memory: "512m"
    labels:
      version: 2.4.0
    serviceAccount: spark
    volumeMounts:
    - name: "test-volume"
      mountPath: "/tmp"
  executor:
    cores: 2
    instances: 3
    memory: "512m"
    labels:
      version: 2.4.0
    volumeMounts:
    - name: "test-volume"
      mountPath: "/tmp"
```

**Comment by liyinan926** [comment]
@doctapp did you also install the operator using the Helm Chart?

**Comment by doctapp** [comment]
@liyinan926 yes used helm with all instructions mentioned.

**Comment by liyinan926** [comment]
@doctapp have you seen the following error in your operator logs?

```
failed to run spark-submit for SparkApplication default/spark-pi: failed to run spark-submit for SparkApplication default/spark-pi: Exception in thread "main" io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://10.16.0.1/api/v1/namespaces/default/pods. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. pods "spark-pi-driver" is forbidden: error looking up service account default/spark: serviceaccount "spark" not found.
```

**Comment by zwennesm** [comment]
@liyinan926 I checked the logs and I only get the `SocketTimeout` exceptions. I've tried the following steps and I still get the same error:

**Command used to install Spark operator**
```
helm install incubator/sparkoperator --name spark-op --set enable-metrics=true --set enableWebhook=true
```

**Job executed**
```
apiVersion: "sparkoperator.k8s.io/v1beta1"
kind: SparkApplication
metadata:
  name: spark-pi
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: "gcr.io/spark-operator/spark:v2.4.0"
  imagePullPolicy: Always
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///opt/spark/examples/jars/spark-examples_2.11-2.4.0.jar"
  sparkVersion: "2.4.0"
  restartPolicy:
    type: Never
  volumes:
    - name: config-vol
      configMap:
        name: dummy-cm
  driver:
    cores: 0.1
    coreLimit: "200m"
    memory: "512m"
    labels:
      version: 2.4.0
    serviceAccount: spark-op-spark
    volumeMounts:
      - name: config-vol
        mountPath: /opt/spark/mycm
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 2.4.0
    volumeMounts:
      - name: config-vol
        mountPath: /opt/spark/mycm
```

**Result (logs from spark operator)**
```
} map[] 0 1}] to [{  2019-08-12 09:55:11 +0000 UTC 0001-01-01 00:00:00 +0000 UTC { 0    } {FAILED failed to run spark-submit for SparkApplication default/spark-pi: Exception in thread "main" io.fabric8.kubernetes.client.KubernetesClientException: Operation: [create]  for kind: [Pod]  with name: [null]  in namespace: [default]  failed.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:62)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:71)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:363)
	at org.apache.spark.deploy.k8s.submit.Client$$anonfun$run$2.apply(KubernetesClientApplication.scala:141)
	at org.apache.spark.deploy.k8s.submit.Client$$anonfun$run$2.apply(KubernetesClientApplication.scala:140)
	at org.apache.spark.util.Utils$.tryWithResource(Utils.scala:2543)
	at org.apache.spark.deploy.k8s.submit.Client.run(KubernetesClientApplication.scala:140)
	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication$$anonfun$run$5.apply(KubernetesClientApplication.scala:250)
	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication$$anonfun$run$5.apply(KubernetesClientApplication.scala:241)
	at org.apache.spark.util.Utils$.tryWithResource(Utils.scala:2543)
	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.run(KubernetesClientApplication.scala:241)
	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.start(KubernetesClientApplication.scala:204)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:849)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.net.SocketTimeoutException: timeout
	at okio.Okio$4.newTimeoutException(Okio.java:230)
	at okio.AsyncTimeout.exit(AsyncTimeout.java:285)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:345)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:211)
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:75)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at io.fabric8.kubernetes.client.utils.HttpClientUtils$2.intercept(HttpClientUtils.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
	at okhttp3.RealCall.execute(RealCall.java:69)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:377)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:343)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:226)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:769)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:356)
	... 16 more
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketInputStream.read(SocketInputStream.java:204)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	... 43 more
```

Everything seems to be working fine when I skip the mutable admission webhook. Could it be the case that the Kubernetes API is closed off? Or do we need to enable additional features on the Kubernetes cluster on GCP? For instance something like ` Kubernetes alpha features ` or `Binary Authorization`?

**Comment by liyinan926** [comment]
@zwennesm no, you shouldn't need any special setup to make it work.

**Comment by zwennesm** [comment]
@liyinan926 It does seem to create a service account in the default namespace.

```
NAME                     SECRETS   AGE
default                  1         271d
spark-op-spark           1         117s
spark-op-sparkoperator   1         117s

~ at ☸️  bijenkorf-dev 
➜ k describe sa spark-op-spark
Name:                spark-op-spark
Namespace:           default
Labels:              app.kubernetes.io/instance=spark-op
                     app.kubernetes.io/managed-by=Tiller
                     app.kubernetes.io/name=sparkoperator
                     helm.sh/chart=sparkoperator-0.2.4
Annotations:         <none>
Image pull secrets:  <none>
Mountable secrets:   spark-op-spark-token-xswqk
Tokens:              spark-op-spark-token-xswqk
Events:              <none>
```
In my initial issue report I did use the `sparkJobNamespace` parameter, but with that settings I am getting the exact same error. Would it be worth a shot to try and install the Spark operator without the use of the Helm templates?

**Comment by liyinan926** [comment]
Yes, I think it worths trying out installation through the manifest in the operator repo.

**Comment by doctapp** [comment]
> @doctapp have you seen the following error in your operator logs?
> 
> ```
> failed to run spark-submit for SparkApplication default/spark-pi: failed to run spark-submit for SparkApplication default/spark-pi: Exception in thread "main" io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://10.16.0.1/api/v1/namespaces/default/pods. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. pods "spark-pi-driver" is forbidden: error looking up service account default/spark: serviceaccount "spark" not found.
> ```
> 
> I saw `serviceAccount` was set to `spark` in the test `SparkApplication` you used. Can you check if that service account exists in namespace `spark-operator`, which is the namespace of your `SparkApplication`.
> 
> BTW: I could not reproduce the issue you ran into. I was able to mount the test volume using the latest Helm version on GKE 1.12.8-gke.10.

The `spark` service account is in the `spark-operator` namespace. Here are the commands I used to create my cluster and deploy the spark operator:

```
gcloud beta container --project xxx clusters create gke-spark-test --zone us-xxx --no-enable-basic-auth --cluster-version "1.12.8-gke.10" --machine-type n1-standard-4 --image-type "COS" --num-nodes 3 --enable-stackdriver-kubernetes --enable-private-nodes --enable-private-endpoint --master-ipv4-cidr x.x.x.x/x --enable-ip-alias --network "xxx" --subnetwork "xxx" --enable-master-authorized-networks --master-authorized-networks x.x.x.x/x --addons KubernetesDashboard --maintenance-window 03:00 --enable-autoupgrade --enable-autorepair
kubectl create serviceaccount --namespace kube-system tiller
kubectl create clusterrolebinding tiller-cluster-role --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
helm init
kubectl patch deploy --namespace kube-system tiller-deploy -p '{"spec":{"template":{"spec":{"serviceAccount":"tiller"}}}}'
kubectl create namespace spark-operator
kubectl create serviceaccount spark -n spark-operator
kubectl create clusterrolebinding spark-role --clusterrole=cluster-admin --serviceaccount=spark-operator:spark --namespace=spark-operator
helm repo add incubator http://storage.googleapis.com/kubernetes-charts-incubator
helm install incubator/sparkoperator --namespace spark-operator --set sparkJobNamespace=spark-operator --set imagePullPolicy=Always --set enableWebhook=true
```

**Comment by liyinan926** [comment]
@doctapp you don't need to manually create a service account and a role binding. The Helm installation will create a service account and role binding in the namespace `spark-operator` for you. In your case, the service account will be named `spark-operator-spark`.

**Comment by liyinan926** [comment]
@doctapp and @zwennesm if you could try installing the operator using the manifest following the instruction below, it would help determining if the issue you ran into is with the Helm chart:

```
# cd spark-on-k8s-operator
# kubectl apply -f manifest/spark-operator-rbac.yaml
# kubectl apply -f manifest/spark-operator-with-webhook.yaml
# kubectl apply -f manifest/spark-rbac.yaml
```

This will setup up RBAC and install the operator into the namespace `spark-operator`. It will also create a service account named `spark` in the `default` namespace for your Spark applications. To test the setup, run the example application:

```
kubectl apply -f examples/spark-pi.yaml
```

**Comment by zwennesm** [comment]
@liyinan926 Following the exact steps you mentioned I still get the same error as before:
```
} map[] 0 1}] to [{  2019-08-12 19:45:47 +0000 UTC 0001-01-01 00:00:00 +0000 UTC { 0    } {FAILED failed to run spark-submit for SparkApplication default/spark-pi: Exception in thread "main" io.fabric8.kubernetes.client.KubernetesClientException: Operation: [create]  for kind: [Pod]  with name: [null]  in namespace: [default]  failed.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:62)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:71)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:363)
	at org.apache.spark.deploy.k8s.submit.Client$$anonfun$run$2.apply(KubernetesClientApplication.scala:141)
	at org.apache.spark.deploy.k8s.submit.Client$$anonfun$run$2.apply(KubernetesClientApplication.scala:140)
	at org.apache.spark.util.Utils$.tryWithResource(Utils.scala:2543)
	at org.apache.spark.deploy.k8s.submit.Client.run(KubernetesClientApplication.scala:140)
	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication$$anonfun$run$5.apply(KubernetesClientApplication.scala:250)
	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication$$anonfun$run$5.apply(KubernetesClientApplication.scala:241)
	at org.apache.spark.util.Utils$.tryWithResource(Utils.scala:2543)
	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.run(KubernetesClientApplication.scala:241)
	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.start(KubernetesClientApplication.scala:204)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:849)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.net.SocketTimeoutException: timeout
	at okio.Okio$4.newTimeoutException(Okio.java:230)
	at okio.AsyncTimeout.exit(AsyncTimeout.java:285)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:345)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:211)
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:75)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at io.fabric8.kubernetes.client.utils.HttpClientUtils$2.intercept(HttpClientUtils.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
	at okhttp3.RealCall.execute(RealCall.java:69)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:377)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:343)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:226)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:769)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:356)
	... 16 more
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketInputStream.read(SocketInputStream.java:204)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	... 43 more
} map[] 0 1}]
I0812 19:45:47.219246       9 controller.go:253] Ending processing key: "default/spark-pi"
```

Now could it be that one of the additional GKE settings are interfering with the mutating admission webhooks feature? We have the following settings enabled in our cluster: `VPC-native (alias IP)`, `Private cluster`. And additionally we disabled the `HTTP load balancing` feature.

**Comment by liyinan926** [comment]
It could be because of the cluster settings. One more ask, could you create a temporary standard cluster and try it again? If it works, it's clearly that certain cluster settings will interfere with the mutating webhook.

**Comment by liyinan926** [comment]
Found this https://github.com/kubernetes/autoscaler/issues/1820.

**Comment by doctapp** [comment]
> @doctapp you don't need to manually create a service account and a role binding. The Helm installation will create a service account and role binding in the namespace `spark-operator` for you. In your case, the service account will be named `spark-operator-spark`. Let me know if using the service account `spark-operator-spark` works for you.

Tried that and am now getting: "error looking up service account spark-operator/spark-operator-spark: serviceaccount "spark-operator-spark" not found"

**Comment by liyinan926** [comment]
@doctapp interesting. Can you list all the service accounts in namespace `spark-operator`?

**Comment by liyinan926** [comment]
@zwennesm @doctapp I think you both ran into the same issue with webhooks on a private cluster.  The default port for the webhook service is 8080, which seems not allowed for private clusters according to https://github.com/kubernetes/autoscaler/issues/1820. We do allow changing the port through the parameter `webhookPort `. Can you try doing the Helm installation with the following flag?

```
--set webhookPort=443
```

**Comment by zwennesm** [comment]
@liyinan926 Changing the port to 443 using the attribute you suggested worked! I tested it using the following Helm command:

```
helm install incubator/sparkoperator --name spark-operator --namespace spark --set sparkJobNamespace=spark --set enable-metrics=true --set enableWebhook=true --set webhookPort=443
```

@doctapp this will create a service account in the spark namespace named `spark-operator-spark`:

```
➜ k get sa -n spark
NAME                           SECRETS   AGE
default                        1         89m
spark-operator-spark           1         89m
spark-operator-sparkoperator   1         89m
```
FYI: To make it work you have to change the namespace of the actual `SparkApplication` to run in the same namespace where you configured the service-account and the `sparkJobNamespace` to be. The `SparkApplication` below works for me.

```
apiVersion: "sparkoperator.k8s.io/v1beta1"
kind: SparkApplication
metadata:
  name: spark-pi
  namespace: spark
spec:
  type: Scala
  mode: cluster
  image: "gcr.io/spark-operator/spark:v2.4.0"
  imagePullPolicy: Always
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///opt/spark/examples/jars/spark-examples_2.11-2.4.0.jar"
  sparkVersion: "2.4.0"
  restartPolicy:
    type: Never
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
  driver:
    cores: 0.1
    coreLimit: "200m"
    memory: "512m"
    labels:
      version: 2.4.0
    serviceAccount: spark-operator-spark
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 2.4.0
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
```

Thanks a lot for your patience and help @liyinan926. You really helped me out. Should I create a PR in the GCP docs to explain this issue?

**Comment by doctapp** [comment]
@zwennesm Had to use `--name spark-operator` otherwise it gets a random name which I didn't check. Many thanks :)
@liyinan926 I too confirm that `--set webhookPort=443` works. Thanks a lot for finding this :)

**Comment by liyinan926** [comment]
Cool! @zwennesm I was also thinking about updating the doc. It would be great if you can create a PR. Thanks!

**Comment by liyinan926** [comment]
Closing this and looking forward to the PR for doc enhancement. Thanks!

**Comment by gaocegege** [comment]
I still have the problem when I disable the mutation webhook. Used to set a larger memory for the operator and solved it. Now it comes again.

spark-operator:v2.4.0

**Comment by gaocegege** [comment]
It is solved by set `export KUBERNETES_REQUEST_TIMEOUT=100000`

**Comment by marwanfahmi** [comment]
Hello @liyinan926 & All,

I ran into the same issue and wanted to perform a clean reinstallation with the solution provided (setting the webhook port), what do I need to do to achieve this? What are the uninstallation steps of the operator to do before executing the reinstallation? Thanks in advance.

**Comment by tmclouisluk** [comment]
> It is solved by `export KUBERNETES_REQUEST_TIMEOUT=100000`
> 
> which is the environment variable for https://github.com/fabric8io/kubernetes-client#configuring-the-client

May I know how to set KUBERNETES_REQUEST_TIMEOUT env variable?

**Comment by kehao95** [comment]
I came across the same issue. And setting the webhook port works for me.
`--set webhookPort=443`

**Comment by fisache** [comment]
FYI: `webhookPort` is changed to `webhook.port`
for example, `--set webhook.port=443`
