### ISSUE TITLE
Unable to run Spark jobs on minikube

### ISSUE THREAD

**Issue by ashkan-leo** [GoogleCloudPlatform/spark-on-k8s-operator#761]
Hello!
Is there a tutorial to follow on how to run a Spark application on top of minikube?
I have been able to run the spark-pi example successfully in minikube. However, I can't make it work for my simple application.
```

If I don't specify the master url when creating the spark session I get the following error:
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/docker/lib/io.7mind.izumi.logstage-adapter-slf4j_2.12-0.9.5-M5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/docker/lib/org.slf4j.slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [izumi.logstage.adapter.slf4j.LogstageLoggerFactory]
I 2020-01-05T04:12:12.070 (Logging.scala:54)  o.apache.spark.SparkContext [9:zio-defau…1914572623] Running Spark version 2.4.4
W 2020-01-05T04:12:12.404 (SLF4JLog.java:176)  …adoop.util.NativeCodeLoader [9:zio-defau…1914572623] Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
E 2020-01-05T04:12:12.538  (Logging.scala:91)  o.apache.spark.SparkContext [9:zio-defau…1914572623] Error initializing SparkContext. {{ org.apache.spark.SparkException: A master URL must be set in your configuration }}
org.apache.spark.SparkException: A master URL must be set in your configuration
        at org.apache.spark.SparkContext.<init>(SparkContext.scala:368)
        at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2520)
        at org.apache.spark.sql.SparkSession$Builder.$anonfun$getOrCreate$5(SparkSession.scala:935)
        at scala.Option.getOrElse(Option.scala:138)
        at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:926)
        at io.baz.polygon.app.DownloadAllDailyApp$.$anonfun$logic$1(DownloadAllDailyApp.scala:57)
        at zio.internal.FiberContext.evaluateNow(FiberContext.scala:295)
        at zio.internal.FiberContext.$anonfun$fork$1(FiberContext.scala:595)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

E 2020-01-05T04:12:12.548  (Logging.scala:91)  o.a.spark.util.Utils [9:zio-defau…1914572623] Uncaught exception in thread zio-default-async-1-1914572623 {{ java.lang.NullPointerException }}
java.lang.NullPointerException
        at org.apache.spark.SparkContext.postApplicationEnd(SparkContext.scala:2416)
        at org.apache.spark.SparkContext.$anonfun$stop$2(SparkContext.scala:1931)
        at org.apache.spark.util.Utils$.tryLogNonFatalError(Utils.scala:1340)
        at org.apache.spark.SparkContext.stop(SparkContext.scala:1931)
        at org.apache.spark.SparkContext.<init>(SparkContext.scala:585)
        at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2520)
        at org.apache.spark.sql.SparkSession$Builder.$anonfun$getOrCreate$5(SparkSession.scala:935)
        at scala.Option.getOrElse(Option.scala:138)
        at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:926)
        at io.baz.polygon.app.DownloadAllDailyApp$.$anonfun$logic$1(DownloadAllDailyApp.scala:57)
        at zio.internal.FiberContext.evaluateNow(FiberContext.scala:295)
        at zio.internal.FiberContext.$anonfun$fork$1(FiberContext.scala:595)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

When I specify the master URL in my code, I get the following exception:

```
E 2020-01-05T04:18:22.130  (Logging.scala:91)  o.apache.spark.SparkContext [9:zio-defau…1914572623] Error initializing SparkContext. {{ org.apache.spark.SparkException: Could not parse Master URL: 'k8s://http://127.0.0.1:8001' }}
org.apache.spark.SparkException: Could not parse Master URL: 'k8s://http://127.0.0.1:8001'
        at org.apache.spark.SparkContext$.org$apache$spark$SparkContext$$createTaskScheduler(SparkContext.scala:2784)
        at org.apache.spark.SparkContext.<init>(SparkContext.scala:493)
        at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2520)
        at org.apache.spark.sql.SparkSession$Builder.$anonfun$getOrCreate$5(SparkSession.scala:935)
        at scala.Option.getOrElse(Option.scala:138)
        at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:926)
        at io.baz.polygon.app.DownloadAllDailyApp$.$anonfun$logic$1(DownloadAllDailyApp.scala:57)
        at zio.internal.FiberContext.evaluateNow(FiberContext.scala:295)
        at zio.internal.FiberContext.$anonfun$fork$1(FiberContext.scala:595)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)


```

The base image I use is created using the instruction here: https://spark.apache.org/docs/latest/running-on-kubernetes.html.

Here is the SparkApplication definition:
```
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: hellobaz
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: polygon:0.1
  imagePullPolicy: IfNotPresent
  mainClass: io.baz.polygon.app.DownloadAllDailyApp
  mainApplicationFile: "local:///opt/docker/lib/polygon.polygon-0.1.jar"
  sparkVersion: "2.4.4"
  restartPolicy:
    type: Never
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
  driver:
    cores: 1
    # coreLimit: "1200m"
    memory: "2g"
    labels:
      version: 2.4.4
    serviceAccount: spark
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 2.4.4
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"

```

Any help would be appreciated.

**Comment by huineng** [comment]
on local (k8 docker for mac using python i always specify local

spark = SparkSession.builder.master("local")  or spark = SparkSession.builder.master("local[12]") to run parallel

**Comment by ashkan-leo** [comment]
Thanks for your response @huineng 
My understanding is that setting master to be "local" will run spark in a local cluster and will not run it using the minikube cluster. I like to use the minikube cluster to run the spark jobs.

**Comment by liyinan926** [comment]
Why do you need to specify the master in your application? Generally your app should inherit the master URL from the command-line arguments. In the case of Spark on k8s, the driver runs `spark-submit` in client mode with the master URL set correctly so you shouldn't need to worry about setting it. Have you tried doing something like the following in your app code?

```
val spark = SparkSession
      .builder
      .appName("SparkLR")
      .getOrCreate()
```

**Comment by huineng** [comment]
the problem i have (on k8 for docker for mac) is that if i don't set it , it will try to spin off an executor on another node (driver on one node, executor on another) but on my local k8 1 only have one node, so i get the error that only one node is available

what setting do i need to set so that as executor as driver can be running on the same node

thanks

**Comment by liyinan926** [comment]
I see. In this case you can try increasing the cpu/memory resources available to minikube and also limit the resource request for the executor.
