### ISSUE TITLE
how to enable  SparkApplications in every namespaces.

### ISSUE THREAD

**Issue by tingweiwu** [GoogleCloudPlatform/spark-on-k8s-operator#801]
I deploy the SparkApplication and sparkoperator follow the yaml here [manifest](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/tree/master/manifest)

and when I create the pi test [spark-py-pi.yaml](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/examples/spark-py-pi.yaml) with default namespace. it run success. but change to another namespace it failed.

here is the logs from sparkoperator
```
kubectl logs sparkoperator-59f4d8b744-d2snq -n spark-operator
++ id -u
+ myuid=0
++ id -g
+ mygid=0
+ set +e
++ getent passwd 0
0
0
root:x:0:0:root:/root:/bin/bash
+ uidentry=root:x:0:0:root:/root:/bin/bash
+ set -e
+ echo 0
+ echo 0
+ echo root:x:0:0:root:/root:/bin/bash
+ [[ -z root:x:0:0:root:/root:/bin/bash ]]
+ exec /usr/bin/tini -s -- /usr/bin/spark-operator -logtostderr
I0211 11:53:15.342991      10 main.go:136] Starting the Spark Operator
I0211 11:53:15.343563      10 main.go:210] Starting application controller goroutines
I0211 11:53:15.343577      10 controller.go:155] Starting the workers of the SparkApplication controller
I0211 11:53:15.443744      10 controller.go:96] Starting the ScheduledSparkApplication controller
I0211 11:53:15.543971      10 controller.go:102] Starting the workers of the ScheduledSparkApplication controller
I0211 11:57:14.341931      10 controller.go:179] SparkApplication system/spark-pi was added, enqueueing it for submission
E0211 11:57:16.378067      10 controller.go:664] failed to run spark-submit for SparkApplication system/spark-pi: failed to run spark-submit for SparkApplication system/spark-pi: log4j:WARN No appenders could be found for logger (io.fabric8.kubernetes.client.Config).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Exception in thread "main" io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://10.96.0.1/api/v1/namespaces/system/pods. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. pods "spark-pi-driver" is forbidden: error looking up service account system/spark: serviceaccount "spark" not found.
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:510)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:447)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:413)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:372)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:241)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:819)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:334)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:330)
	at org.apache.spark.deploy.k8s.submit.Client$$anonfun$run$2.apply(KubernetesClientApplication.scala:141)
	at org.apache.spark.deploy.k8s.submit.Client$$anonfun$run$2.apply(KubernetesClientApplication.scala:140)
	at org.apache.spark.util.Utils$.tryWithResource(Utils.scala:2543)
	at org.apache.spark.deploy.k8s.submit.Client.run(KubernetesClientApplication.scala:140)
	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication$$anonfun$run$5.apply(KubernetesClientApplication.scala:250)
	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication$$anonfun$run$5.apply(KubernetesClientApplication.scala:241)
	at org.apache.spark.util.Utils$.tryWithResource(Utils.scala:2543)
	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.run(KubernetesClientApplication.scala:241)
	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.start(KubernetesClientApplication.scala:204)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:845)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
20/02/11 11:57:16 INFO ShutdownHookManager: Shutdown hook called
20/02/11 11:57:16 INFO ShutdownHookManager: Deleting directory /tmp/spark-15669a96-1586-4f69-ac2f-851ec1acf340
E0211 11:57:16.388181      10 controller.go:753] failed to update SparkApplication system/spark-pi: SparkApplication.sparkoperator.k8s.io "spark-pi" is invalid: []: Invalid value: map[string]interface {}{"spec":map[string]interface {}{"imagePullPolicy":"IfNotPresent", "mainClass":"org.apache.spark.examples.SparkPi", "restartPolicy":map[string]interface {}{"type":"Never"}, "sparkVersion":"2.4.4", "type":"Scala", "volumes":[]interface {}{map[string]interface {}{"hostPath":map[string]interface {}{"type":"Directory", "path":"/tmp"}, "name":"test-volume"}}, "executor":map[string]interface {}{"cores":1, "instances":1, "labels":map[string]interface {}{"version":"2.4.4"}, "memory":"512m", "volumeMounts":[]interface {}{map[string]interface {}{"mountPath":"/tmp", "name":"test-volume"}}}, "mainApplicationFile":"local:///opt/spark/examples/jars/spark-examples_2.11-2.4.4.jar", "image":"train.registry.docker.com:5000/spark:v2.4.4", "mode":"cluster", "driver":map[string]interface {}{"volumeMounts":[]interface {}{map[string]interface {}{"mountPath":"/tmp", "name":"test-volume"}}, "coreLimit":"1200m", "cores":1, "labels":map[string]interface {}{"version":"2.4.4"}, "memory":"512m", "serviceAccount":"spark"}}, "apiVersion":"sparkoperator.k8s.io/v1beta2", "kind":"SparkApplication", "metadata":map[string]interface {}{"generation":1, "creationTimestamp":"2020-02-11T11:57:14Z", "resourceVersion":"1101323", "name":"spark-pi", "namespace":"system", "uid":"a4ad41e8-4cc5-11ea-b2d5-fa163e9d0f1f"}, "status":map[string]interface {}{"lastSubmissionAttemptTime":"2020-02-11T11:57:16Z", "terminationTime":interface {}(nil), "driverInfo":map[string]interface {}{}, "applicationState":map[string]interface {}{"state":"SUBMISSION_FAILED", "errorMessage":"failed to run spark-submit for SparkApplication system/spark-pi: log4j:WARN No appenders could be found for logger (io.fabric8.kubernetes.client.Config).\nlog4j:WARN Please initialize the log4j system properly.\nlog4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.\nUsing Spark's default log4j profile: org/apache/spark/log4j-defaults.properties\nException in thread \"main\" io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://10.96.0.1/api/v1/namespaces/system/pods. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. pods \"spark-pi-driver\" is forbidden: error looking up service account system/spark: serviceaccount \"spark\" not found.\n\tat io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:510)\n\tat io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:447)\n\tat io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:413)\n\tat io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:372)\n\tat io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:241)\n\tat io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:819)\n\tat io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:334)\n\tat io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:330)\n\tat org.apache.spark.deploy.k8s.submit.Client$$anonfun$run$2.apply(KubernetesClientApplication.scala:141)\n\tat org.apache.spark.deploy.k8s.submit.Client$$anonfun$run$2.apply(KubernetesClientApplication.scala:140)\n\tat org.apache.spark.util.Utils$.tryWithResource(Utils.scala:2543)\n\tat org.apache.spark.deploy.k8s.submit.Client.run(KubernetesClientApplication.scala:140)\n\tat org.apache.spark.deploy.k8s.submit.KubernetesClientApplication$$anonfun$run$5.apply(KubernetesClientApplication.scala:250)\n\tat org.apache.spark.deploy.k8s.submit.KubernetesClientApplication$$anonfun$run$5.apply(KubernetesClientApplication.scala:241)\n\tat org.apache.spark.util.Utils$.tryWithResource(Utils.scala:2543)\n\tat org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.run(KubernetesClientApplication.scala:241)\n\tat org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.start(KubernetesClientApplication.scala:204)\n\tat org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:845)\n\tat org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)\n\tat org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)\n\tat org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)\n\tat org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)\n\tat org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)\n\tat org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)\n20/02/11 11:57:16 INFO ShutdownHookManager: Shutdown hook called\n20/02/11 11:57:16 INFO ShutdownHookManager: Deleting directory /tmp/spark-15669a96-1586-4f69-ac2f-851ec1acf340\n"}, "submissionAttempts":1}}: validation failure list:
status.terminationTime in body must be of type string: "null"

```

**Comment by liyinan926** [comment]
You will need to setup RBAC for every namespaces where you want to run `SparkApplication`s. Specifically, you need to apply `manifest/spark-rbac.yaml` to the namespaces.

**Comment by pudong7163** [comment]
@liyinan926 Thanks for your clarification! May I ask a follow up question?

I deployed the operator in namespace A (without specifying sparkJobNamespace). In namespace B, I applied the spark-rbac.yaml without creating a serviceaccount in namespace B. Instead, I referred to the serviceaccount created in the A. 

With this setup, the creation of a SparkApplication failed. And it complained that the serviceaccount was missing/revoked in namespace B. 

The log is below. I used default namespace for namespace B.
```
Failure executing: POST at: https://10.96.0.1/api/v1/namespaces/default/pods. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. pods "spark-pi-driver" is forbidden: error looking up service account default/sparkoperator-spark: serviceaccount "sparkoperator-spark" not found.
```

The spark-rbac.yaml I applied.
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: spark-role
rules:
- apiGroups:
  - "" # "" indicates the core API group
  resources:
  - "pods"
  verbs:
  - "*"
- apiGroups:
  - "" # "" indicates the core API group
  resources:
  - "services"
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: sparkoperator-spark
  namespace: namespaceA
roleRef:
  kind: Role
  name: spark-role
  apiGroup: rbac.authorization.k8s.io
```

I think I need to create the serviceaccount too for namespace B?

Thanks for your time. Much appreciate it!

**Comment by liyinan926** [comment]
The RBAC settings for the driver including the service account, the role, and the role binding are namespaced so you will need to apply them in every namespace you want to deploy spark applications in. If you specify `sparkJobNamespace`, then the operator will only handle `SparkApplication`s in that namespace, and RBAC for the namespace will be automatically setup.

**Comment by pudong7163** [comment]
@liyinan926 Thanks for the reply. I think what your said confirmed my reading and my experiments. I need to create service account myself for every namespace I plan to start `SparkApplication` in.

**Comment by tingweiwu** [comment]
@liyinan926 I have applied `manifest/spark-rbac.yaml` to the namespaces and 
recreate the pi test `spark-py-pi.yaml`

```
kubectl get pods -n system
NAME                READY   STATUS    RESTARTS   AGE
pyspark-pi-driver   1/1     Running   0          2m57s
```
and get the error from the driver as the `Resource Quotas` have been setted in namespace `system`
```
20/02/13 12:15:10 ERROR Utils: Uncaught exception in thread kubernetes-executor-snapshots-subscribers-1
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://kubernetes.default.svc/api/v1/namespaces/system/pods. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. pods "pyspark-pi-1581596092621-exec-1" is forbidden: failed quota: system-resourcequota: must specify limits.cpu.

```
I have check the `pyspark-pi-driver ` and `pyspark-pi-1581596745205-exec-1` pod spec where I deploy the pi test `spark-py-pi.yaml` in default namespace 
pyspark-pi-driver
```
    resources:
      limits:
        cpu: 1200m
        memory: 896Mi
      requests:
        cpu: "1"
        memory: 896Mi
```

pyspark-pi-1581596745205-exec-1
```
    resources:
      limits:
        memory: 896Mi
      requests:
        cpu: "1"
        memory: 896Mi
```

so. the exec pod don't set cpu limits?
