### ISSUE TITLE
Enable webhook cause tiller down

### ISSUE THREAD

**Issue by NanXuejiao** [GoogleCloudPlatform/spark-on-k8s-operator#871]
`helm install` with `--set enableWebhook=true`, the tiller pod exits and reports the following.
Without  `--set enableWebhook=true` it works well. 
What's wrong? And how to fix this?
```
[kube] 2020/04/14 04:33:47 get relation pod of object: spark-operator/Deployment/test-sparkoperator
[kube] 2020/04/14 04:33:47 get relation pod of object: spark-operator/Job/test-sparkoperator-webhook-init
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x14e31de]

goroutine 1562 [running]:
k8s.io/helm/pkg/kube.getSelectorFromObject(0x1c00c00, 0xc000b00480, 0xc000b00480, 0x0)
	/go/src/k8s.io/helm/pkg/kube/client.go:931 +0x2fe
k8s.io/helm/pkg/kube.(*Client).getSelectRelationPod(0xc0003cea20, 0xc000abe0e0, 0xc000606930, 0xc0008c4fd0, 0x18, 0xc00079fe48)
	/go/src/k8s.io/helm/pkg/kube/client.go:1104 +0x195
k8s.io/helm/pkg/kube.(*Client).Get.func2(0xc000abe0e0, 0x0, 0x0)
	/go/src/k8s.io/helm/pkg/kube/client.go:366 +0xd1
k8s.io/helm/pkg/kube.batchPerform.func1(0xc000e107e0, 0xc000aabf50, 0xc0005e12b0, 0xc000abe0e0)
	/go/src/k8s.io/helm/pkg/kube/client.go:752 +0x30
created by k8s.io/helm/pkg/kube.batchPerform
	/go/src/k8s.io/helm/pkg/kube/client.go:751 +0xb8
```

**Comment by NanXuejiao** [comment]
My install conmmand:
```
helm install incubator/sparkoperator --name test \
 --namespace spark-operator \
 --set enableWebhook=true \
 --set sparkJobNamespace=job \
 --set operatorImageName=xxx/spark-operator \
 --set operatorVersion=v1beta2-1.1.1-2.4.5
```

**Comment by NanXuejiao** [comment]
Close.
Helm version v2.16.5 caused this.  downgrade to v2.16.3 it works.
