### ISSUE TITLE
runtime error: index out of range

### ISSUE THREAD

**Issue by camper42** [GoogleCloudPlatform/spark-on-k8s-operator#927]
base spark image: 3.0.0-rc2
spark-on-k8s-operator: current master(8c480ac)

```
I0527 15:43:43.258750       9 webhook.go:246] Serving admission request
2020/05/27 15:43:43 http: panic serving 172.18.4.56:56240: runtime error: index out of range [1] with length 1
goroutine 465 [running]:
net/http.(*conn).serve.func1(0xc000239a40)
        /usr/local/go/src/net/http/server.go:1772 +0x139
panic(0x155f660, 0xc000313380)
        /usr/local/go/src/runtime/panic.go:973 +0x3e3
github.com/GoogleCloudPlatform/spark-on-k8s-operator/pkg/webhook.addEnvVars(0xc000d27000, 0xc000c89500, 0x0, 0x5, 0x0)
        /workspace/pkg/webhook/patch.go:213 +0xc7b
github.com/GoogleCloudPlatform/spark-on-k8s-operator/pkg/webhook.patchSparkPod(0xc000d27000, 0xc000c89500, 0x19, 0xc000c89500, 0x0)
        /workspace/pkg/webhook/patch.go:63 +0x929
github.com/GoogleCloudPlatform/spark-on-k8s-operator/pkg/webhook.mutatePods(0xc000471080, 0x1835d20, 0xc00068e960, 0x0, 0x0, 0x1837260, 0xc000471080, 0x1837260)
        /workspace/pkg/webhook/webhook.go:554 +0x591
github.com/GoogleCloudPlatform/spark-on-k8s-operator/pkg/webhook.(*WebHook).serve(0xc000152000, 0x1866a60, 0xc000410fc0, 0xc000774500)
        /workspace/pkg/webhook/webhook.go:278 +0xb1a
net/http.HandlerFunc.ServeHTTP(0xc00068e970, 0x1866a60, 0xc000410fc0, 0xc000774500)
        /usr/local/go/src/net/http/server.go:2012 +0x44
net/http.(*ServeMux).ServeHTTP(0xc00032e200, 0x1866a60, 0xc000410fc0, 0xc000774500)
        /usr/local/go/src/net/http/server.go:2387 +0x1a5
net/http.serverHandler.ServeHTTP(0xc0002802a0, 0x1866a60, 0xc000410fc0, 0xc000774500)
        /usr/local/go/src/net/http/server.go:2807 +0xa3
net/http.(*conn).serve(0xc000239a40, 0x1869460, 0xc000309540)
        /usr/local/go/src/net/http/server.go:1895 +0x86c
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2933 +0x35c
```

task failed due to `20/05/27 15:48:08 WARN TaskSetManager: Lost task 47.0 in stage 1.0 (TID 38, 172.18.12.113, executor 1): org.apache.hadoop.security.AccessControlException: Permission denied: user=5089, access=WRITE, inode="/user/camper42/streaming_checkpoint/query2":camper42:supergroup:drwxr-xr-x`

5089 is `spark_uid` in spark Dockerfile, and I set `runAsUser: 3631`

**Comment by camper42** [comment]
our executor pod's executor container name is `spark-kubernetes-executor`

https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/pkg/webhook/patch.go#L203 not work, and index out of range at line 213

**Comment by liyinan926** [comment]
This has been fixed in https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/876. It will be included in the next release.

**Comment by liyinan926** [comment]
Looks like #876 missed some places. Will create a PR to fix.

**Comment by camper42** [comment]
thx
